RAID = [
    "𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗚𝗛𝗨𝗧𝗞𝗔 𝗞𝗛𝗔𝗔𝗞𝗘 𝗧𝗛𝗢𝗢𝗞 𝗗𝗨𝗡𝗚𝗔 🤣🤣",
    "𝗧𝗘𝗥𝗘 𝗕𝗘́𝗛𝗘𝗡 𝗞 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗞𝗨 𝗗𝗔𝗔𝗟 𝗞𝗔𝗥 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔 𝗞𝗛𝗢𝗢𝗡 𝗞𝗔𝗥 𝗗𝗨𝗚𝗔",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗡𝗛𝗜 𝗛𝗔𝗜 𝗞𝗬𝗔? 9 𝗠𝗔𝗛𝗜𝗡𝗘 𝗥𝗨𝗞 𝗦𝗔𝗚𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗗𝗘𝗧𝗔 𝗛𝗨 🤣🤣🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗔𝗘𝗥𝗢𝗣𝗟𝗔𝗡𝗘𝗣𝗔𝗥𝗞 𝗞𝗔𝗥𝗞𝗘 𝗨𝗗𝗔𝗔𝗡 𝗕𝗛𝗔𝗥 𝗗𝗨𝗚𝗔 ✈️🛫",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗦𝗨𝗧𝗟𝗜 𝗕𝗢𝗠𝗕 𝗙𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗝𝗛𝗔𝗔𝗧𝗘 𝗝𝗔𝗟 𝗞𝗘 𝗞𝗛𝗔𝗔𝗞 𝗛𝗢 𝗝𝗔𝗬𝗘𝗚𝗜💣",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗦𝗖𝗢𝗢𝗧𝗘𝗥 𝗗𝗔𝗔𝗟 𝗗𝗨𝗚𝗔👅",
    "𝗧𝗘𝗥𝗘 𝗕𝗘́𝗛𝗘𝗡 𝗞 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗞𝗨 𝗗𝗔𝗔𝗟 𝗞𝗔𝗥 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔 𝗞𝗛𝗢𝗢𝗡 𝗞𝗔𝗥 𝗗𝗨𝗚𝗔",
    "𝗧𝗘𝗥𝗘 𝗕𝗘́𝗛𝗘𝗡 𝗞 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗞𝗨 𝗗𝗔𝗔𝗟 𝗞𝗔𝗥 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔 𝗞𝗛𝗢𝗢𝗡 𝗞𝗔𝗥 𝗗𝗨𝗚𝗔",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔𝗞𝗧𝗘 🤱 𝗚𝗔𝗟𝗜 𝗞𝗘 𝗞𝗨𝗧𝗧𝗢 🦮 𝗠𝗘 𝗕𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 𝗣𝗛𝗜𝗥 🍞 𝗕𝗥𝗘𝗔𝗗 𝗞𝗜 𝗧𝗔𝗥𝗛 𝗞𝗛𝗔𝗬𝗘𝗡𝗚𝗘 𝗪𝗢 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧",
    "𝗗𝗨𝗗𝗛 𝗛𝗜𝗟𝗔𝗔𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗘 𝗨𝗣𝗥 𝗡𝗜𝗖𝗛𝗘 🆙🆒😙",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 ✋ 𝗛𝗔𝗧𝗧𝗛 𝗗𝗔𝗟𝗞𝗘 👶 𝗕𝗔𝗖𝗖𝗛𝗘 𝗡𝗜𝗞𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗞𝗘𝗟𝗘 𝗞𝗘 𝗖𝗛𝗜𝗟𝗞𝗘 🍌🍌😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗨𝗦𝗘𝗥𝗕𝗢𝗧 𝗟𝗔𝗚𝗔𝗔𝗨𝗡𝗚𝗔 𝗦𝗔𝗦𝗧𝗘 𝗦𝗣𝗔𝗠 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗗𝗛𝗔𝗡𝗗𝗛𝗘 𝗩𝗔𝗔𝗟𝗜 😋😛",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗔𝗖 𝗟𝗔𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 𝗦𝗔𝗔𝗥𝗜 𝗚𝗔𝗥𝗠𝗜 𝗡𝗜𝗞𝗔𝗟 𝗝𝗔𝗔𝗬𝗘𝗚𝗜",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗛𝗢𝗥𝗟𝗜𝗖𝗞𝗦 𝗣𝗘𝗘𝗟𝗔𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗😚",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗦𝗔𝗥𝗜𝗬𝗔 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗨𝗦𝗜 𝗦𝗔𝗥𝗜𝗬𝗘 𝗣𝗥 𝗧𝗔𝗡𝗚 𝗞𝗘 𝗕𝗔𝗖𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗛𝗢𝗡𝗚𝗘 😱😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗞𝗢𝗟𝗞𝗔𝗧𝗔 𝗩𝗔𝗔𝗟𝗘 𝗝𝗜𝗧𝗨 𝗕𝗛𝗔𝗜𝗬𝗔 𝗞𝗔 𝗟𝗨𝗡𝗗 𝗠𝗨𝗕𝗔𝗥𝗔𝗞 🤩🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗙𝗔𝗡𝗧𝗔𝗦𝗬 𝗛𝗨 𝗟𝗔𝗪𝗗𝗘, 𝗧𝗨 𝗔𝗣𝗡𝗜 𝗕𝗛𝗘𝗡 𝗞𝗢 𝗦𝗠𝗕𝗛𝗔𝗔𝗟 😈😈",
    "𝗧𝗘𝗥𝗔 𝗣𝗘𝗛𝗟𝗔 𝗕𝗔𝗔𝗣 𝗛𝗨 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 ",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗫𝗩𝗜𝗗𝗘𝗢𝗦.𝗖𝗢𝗠 𝗖𝗛𝗔𝗟𝗔 𝗞𝗘 𝗠𝗨𝗧𝗛 𝗠𝗔́𝗔̀𝗥𝗨𝗡𝗚𝗔 🤡😹",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗚𝗥𝗢𝗨𝗣 𝗩𝗔𝗔𝗟𝗢𝗡 𝗦𝗔𝗔𝗧𝗛 𝗠𝗜𝗟𝗞𝗘 𝗚𝗔𝗡𝗚 𝗕𝗔𝗡𝗚 𝗞𝗥𝗨𝗡𝗚𝗔🙌🏻☠️ ",
    "𝗧𝗘𝗥𝗜 𝗜𝗧𝗘𝗠 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗟𝗨𝗡𝗗 𝗗𝗔𝗔𝗟𝗞𝗘,𝗧𝗘𝗥𝗘 𝗝𝗔𝗜𝗦𝗔 𝗘𝗞 𝗢𝗥 𝗡𝗜𝗞𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗🤘🏻🙌🏻☠️ ",
    "𝗔𝗨𝗞𝗔𝗔𝗧 𝗠𝗘 𝗥𝗘𝗛 𝗩𝗥𝗡𝗔 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗗𝗔𝗡𝗗𝗔 𝗗𝗔𝗔𝗟 𝗞𝗘 𝗠𝗨𝗛 𝗦𝗘 𝗡𝗜𝗞𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗦𝗛𝗔𝗥𝗜𝗥 𝗕𝗛𝗜 𝗗𝗔𝗡𝗗𝗘 𝗝𝗘𝗦𝗔 𝗗𝗜𝗞𝗛𝗘𝗚𝗔 🙄🤭🤭",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗘 𝗦𝗔𝗔𝗧𝗛 𝗟𝗨𝗗𝗢 𝗞𝗛𝗘𝗟𝗧𝗘 𝗞𝗛𝗘𝗟𝗧𝗘 𝗨𝗦𝗞𝗘 𝗠𝗨𝗛 𝗠𝗘 𝗔𝗣𝗡𝗔 𝗟𝗢𝗗𝗔 𝗗𝗘 𝗗𝗨𝗡𝗚𝗔☝🏻☝🏻😬",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗔𝗣𝗡𝗘 𝗟𝗨𝗡𝗗 𝗣𝗥 𝗜𝗧𝗡𝗔 𝗝𝗛𝗨𝗟𝗔𝗔𝗨𝗡𝗚𝗔 𝗞𝗜 𝗝𝗛𝗨𝗟𝗧𝗘 𝗝𝗛𝗨𝗟𝗧𝗘 𝗛𝗜 𝗕𝗔𝗖𝗛𝗔 𝗣𝗔𝗜𝗗𝗔 𝗞𝗥 𝗗𝗘𝗚𝗜👀👯 ",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗕𝗔𝗧𝗧𝗘𝗥𝗬 𝗟𝗔𝗚𝗔 𝗞𝗘 𝗣𝗢𝗪𝗘𝗥𝗕𝗔𝗡𝗞 𝗕𝗔𝗡𝗔 𝗗𝗨𝗡𝗚𝗔 🔋 🔥🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗖++ 𝗦𝗧𝗥𝗜𝗡𝗚 𝗘𝗡𝗖𝗥𝗬𝗣𝗧𝗜𝗢𝗡 𝗟𝗔𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 𝗕𝗔𝗛𝗧𝗜 𝗛𝗨𝗬𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗥𝗨𝗞 𝗝𝗔𝗬𝗘𝗚𝗜𝗜𝗜𝗜😈🔥😍",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘𝗜 𝗝𝗛𝗔𝗔𝗗𝗨 𝗗𝗔𝗟 𝗞𝗘 𝗠𝗢𝗥 🦚 𝗕𝗔𝗡𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 🤩🥵😱",
    "𝗧𝗘𝗥𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗦𝗛𝗢𝗨𝗟𝗗𝗘𝗥𝗜𝗡𝗚 𝗞𝗔𝗥 𝗗𝗨𝗡𝗚𝗔𝗔 𝗛𝗜𝗟𝗔𝗧𝗘 𝗛𝗨𝗬𝗘 𝗕𝗛𝗜 𝗗𝗔𝗥𝗗 𝗛𝗢𝗚𝗔𝗔𝗔😱🤮👺",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗥𝗘𝗗𝗜 𝗣𝗘 𝗕𝗔𝗜𝗧𝗛𝗔𝗟 𝗞𝗘 𝗨𝗦𝗦𝗘 𝗨𝗦𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗕𝗜𝗟𝗪𝗔𝗨𝗡𝗚𝗔𝗔 💰 😵🤩",
    "𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 4 𝗛𝗢𝗟𝗘 𝗛𝗔𝗜 𝗨𝗡𝗠𝗘 𝗠𝗦𝗘𝗔𝗟 𝗟𝗔𝗚𝗔 𝗕𝗔𝗛𝗨𝗧 𝗕𝗔𝗛𝗘𝗧𝗜 𝗛𝗔𝗜 𝗕𝗛𝗢𝗙𝗗𝗜𝗞𝗘👊🤮🤢🤢",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗕𝗔𝗥𝗚𝗔𝗗 𝗞𝗔 𝗣𝗘𝗗 𝗨𝗚𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 𝗖𝗢𝗥𝗢𝗡𝗔 𝗠𝗘𝗜 𝗦𝗔𝗕 𝗢𝗫𝗬𝗚𝗘𝗡 𝗟𝗘𝗞𝗔𝗥 𝗝𝗔𝗬𝗘𝗡𝗚𝗘🤢🤩🥳",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗦𝗨𝗗𝗢 𝗟𝗔𝗚𝗔 𝗞𝗘 𝗕𝗜𝗚𝗦𝗣𝗔𝗠 𝗟𝗔𝗚𝗔 𝗞𝗘 9999 𝗙𝗨𝗖𝗞 𝗟𝗔𝗚𝗔𝗔 𝗗𝗨 🤩🥳🔥",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘 𝗠𝗘𝗜 𝗕𝗘𝗦𝗔𝗡 𝗞𝗘 𝗟𝗔𝗗𝗗𝗨 𝗕𝗛𝗔𝗥 𝗗𝗨𝗡𝗚𝗔🤩🥳🔥😈",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗛𝗢𝗗 𝗞𝗘 𝗨𝗦𝗠𝗘 𝗖𝗬𝗟𝗜𝗡𝗗𝗘𝗥 ⛽️ 𝗙𝗜𝗧 𝗞𝗔𝗥𝗞𝗘 𝗨𝗦𝗠𝗘𝗘 𝗗𝗔𝗟 𝗠𝗔𝗞𝗛𝗔𝗡𝗜 𝗕𝗔𝗡𝗔𝗨𝗡𝗚𝗔𝗔𝗔🤩👊🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗦𝗛𝗘𝗘𝗦𝗛𝗔 𝗗𝗔𝗟 𝗗𝗨𝗡𝗚𝗔𝗔𝗔 𝗔𝗨𝗥 𝗖𝗛𝗔𝗨𝗥𝗔𝗛𝗘 𝗣𝗘 𝗧𝗔𝗔𝗡𝗚 𝗗𝗨𝗡𝗚𝗔 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘😈😱🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗖𝗥𝗘𝗗𝗜𝗧 𝗖𝗔𝗥𝗗 𝗗𝗔𝗟 𝗞𝗘 𝗔𝗚𝗘 𝗦𝗘 500 𝗞𝗘 𝗞𝗔𝗔𝗥𝗘 𝗞𝗔𝗔𝗥𝗘 𝗡𝗢𝗧𝗘 𝗡𝗜𝗞𝗔𝗟𝗨𝗡𝗚𝗔𝗔 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘💰💰🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗦𝗔𝗧𝗛 𝗦𝗨𝗔𝗥 𝗞𝗔 𝗦𝗘𝗫 𝗞𝗔𝗥𝗪𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 𝗘𝗞 𝗦𝗔𝗧𝗛 6-6 𝗕𝗔𝗖𝗛𝗘 𝗗𝗘𝗚𝗜💰🔥😱",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗔𝗣𝗣𝗟𝗘 𝗞𝗔 18𝗪 𝗪𝗔𝗟𝗔 𝗖𝗛𝗔𝗥𝗚𝗘𝗥 🔥🤩",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘𝗜 𝗢𝗡𝗘𝗣𝗟𝗨𝗦 𝗞𝗔 𝗪𝗥𝗔𝗣 𝗖𝗛𝗔𝗥𝗚𝗘𝗥 30𝗪 𝗛𝗜𝗚𝗛 𝗣𝗢𝗪𝗘𝗥 💥😂😎",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗢 𝗔𝗠𝗔𝗭𝗢𝗡 𝗦𝗘 𝗢𝗥𝗗𝗘𝗥 𝗞𝗔𝗥𝗨𝗡𝗚𝗔 10 𝗿𝘀 𝗠𝗘𝗜 𝗔𝗨𝗥 𝗙𝗟𝗜𝗣𝗞𝗔𝗥𝗧 𝗣𝗘 20 𝗥𝗦 𝗠𝗘𝗜 𝗕𝗘𝗖𝗛 𝗗𝗨𝗡𝗚𝗔🤮👿😈🤖",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗕𝗔𝗗𝗜 𝗕𝗛𝗨𝗡𝗗 𝗠𝗘 𝗭𝗢𝗠𝗔𝗧𝗢 𝗗𝗔𝗟 𝗞𝗘 𝗦𝗨𝗕𝗪𝗔𝗬 𝗞𝗔 𝗕𝗙𝗙 𝗩𝗘𝗚 𝗦𝗨𝗕 𝗖𝗢𝗠𝗕𝗢 [15𝗰𝗺 , 16 𝗶𝗻𝗰𝗵𝗲𝘀 ] 𝗢𝗥𝗗𝗘𝗥 𝗖𝗢𝗗 𝗞𝗥𝗩𝗔𝗨𝗡𝗚𝗔 𝗢𝗥 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗝𝗔𝗕 𝗗𝗜𝗟𝗜𝗩𝗘𝗥𝗬 𝗗𝗘𝗡𝗘 𝗔𝗬𝗘𝗚𝗜 𝗧𝗔𝗕 𝗨𝗦𝗣𝗘 𝗝𝗔𝗔𝗗𝗨 𝗞𝗥𝗨𝗡𝗚𝗔 𝗢𝗥 𝗙𝗜𝗥 9 𝗠𝗢𝗡𝗧𝗛 𝗕𝗔𝗔𝗗 𝗩𝗢 𝗘𝗞 𝗢𝗥 𝗙𝗥𝗘𝗘 𝗗𝗜𝗟𝗜𝗩𝗘𝗥𝗬 𝗗𝗘𝗚𝗜🙀👍🥳🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗔𝗔𝗟𝗜🙁🤣💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗖𝗛𝗔𝗡𝗚𝗘𝗦 𝗖𝗢𝗠𝗠𝗜𝗧 𝗞𝗥𝗨𝗚𝗔 𝗙𝗜𝗥 𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗔𝗨𝗧𝗢𝗠𝗔𝗧𝗜𝗖𝗔𝗟𝗟𝗬 𝗨𝗣𝗗𝗔𝗧𝗘 𝗛𝗢𝗝𝗔𝗔𝗬𝗘𝗚𝗜🤖🙏🤔",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗨𝗦𝗜 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗜𝗡𝗗𝗜𝗔𝗡 𝗥𝗔𝗜𝗟𝗪𝗔𝗬 🚂💥😂",
    "𝗧𝗨 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗧𝗘𝗥𝗔 𝗞𝗛𝗔𝗡𝗗𝗔𝗡 𝗦𝗔𝗕 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗪𝗗𝗘 𝗥Æ𝗡𝗗𝗜 𝗛𝗔𝗜 𝗥Æ𝗡𝗗𝗜 🤢✅🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗜𝗢𝗡𝗜𝗖 𝗕𝗢𝗡𝗗 𝗕𝗔𝗡𝗔 𝗞𝗘 𝗩𝗜𝗥𝗚𝗜𝗡𝗜𝗧𝗬 𝗟𝗢𝗢𝗦𝗘 𝗞𝗔𝗥𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗨𝗦𝗞𝗜 📚 😎🤩",
    "𝗧𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗠𝗔́𝗔̀ 𝗦𝗘 𝗣𝗨𝗖𝗛𝗡𝗔 𝗕𝗔𝗔𝗣 𝗞𝗔 𝗡𝗔𝗔𝗠 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗢𝗗𝗘𝗘𝗘𝗘𝗘 🤩🥳😳",
    "𝗧𝗨 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗗𝗢𝗡𝗢 𝗞𝗜 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗠𝗘𝗧𝗥𝗢 𝗖𝗛𝗔𝗟𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 🚇🤩😱🥶",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣 𝗕𝗛𝗜 𝗨𝗦𝗞𝗢 𝗣𝗔𝗛𝗖𝗛𝗔𝗡𝗔𝗡𝗘 𝗦𝗘 𝗠𝗔𝗡𝗔 𝗞𝗔𝗥 𝗗𝗘𝗚𝗔😂👿🤩",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗛𝗔𝗜𝗥 𝗗𝗥𝗬𝗘𝗥 𝗖𝗛𝗔𝗟𝗔 𝗗𝗨𝗡𝗚𝗔𝗔💥🔥🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗧𝗘𝗟𝗘𝗚𝗥𝗔𝗠 𝗞𝗜 𝗦𝗔𝗥𝗜 𝗥Æ𝗡𝗗𝗜𝗬𝗢𝗡 𝗞𝗔 𝗥Æ𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗔 𝗞𝗛𝗢𝗟 𝗗𝗨𝗡𝗚𝗔𝗔👿🤮😎",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗔𝗟𝗘𝗫𝗔 𝗗𝗔𝗟 𝗞𝗘𝗘 𝗗𝗝 𝗕𝗔𝗝𝗔𝗨𝗡𝗚𝗔𝗔𝗔 🎶 ⬆️🤩💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗚𝗜𝗧𝗛𝗨𝗕 𝗗𝗔𝗟 𝗞𝗘 𝗔𝗣𝗡𝗔 𝗕𝗢𝗧 𝗛𝗢𝗦𝗧 𝗞𝗔𝗥𝗨𝗡𝗚𝗔𝗔 🤩👊👤😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗩𝗣𝗦 𝗕𝗔𝗡𝗔 𝗞𝗘 24*7 𝗕𝗔𝗦𝗛 𝗖𝗛𝗨𝗗𝗔𝗜 𝗖𝗢𝗠𝗠𝗔𝗡𝗗 𝗗𝗘 𝗗𝗨𝗡𝗚𝗔𝗔 🤩💥🔥🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗧𝗘𝗥𝗘 𝗟𝗔𝗡𝗗 𝗞𝗢 𝗗𝗔𝗟 𝗞𝗘 𝗞𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 🔪😂🔥",
    "𝗦𝗨𝗡 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗜 𝗕𝗛𝗢𝗦𝗗𝗔 👿😎👊",
    "𝗧𝗨𝗝𝗛𝗘 𝗗𝗘𝗞𝗛 𝗞𝗘 𝗧𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗕𝗔𝗛𝗘𝗡 𝗣𝗘 𝗧𝗔𝗥𝗔𝗦 𝗔𝗧𝗔 𝗛𝗔𝗜 𝗠𝗨𝗝𝗛𝗘 𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗢𝗗𝗘𝗘𝗘𝗘 👿💥🤩🔥",
    "𝗦𝗨𝗡 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗝𝗬𝗔𝗗𝗔 𝗡𝗔 𝗨𝗖𝗛𝗔𝗟 𝗠𝗔́𝗔̀ 𝗖𝗛𝗢𝗗 𝗗𝗘𝗡𝗚𝗘 𝗘𝗞 𝗠𝗜𝗡 𝗠𝗘𝗜 ✅🤣🔥🤩",
    "𝗔𝗣𝗡𝗜 𝗔𝗠𝗠𝗔 𝗦𝗘 𝗣𝗨𝗖𝗛𝗡𝗔 𝗨𝗦𝗞𝗢 𝗨𝗦 𝗞𝗔𝗔𝗟𝗜 𝗥𝗔𝗔𝗧 𝗠𝗘𝗜 𝗞𝗔𝗨𝗡 𝗖𝗛𝗢𝗗𝗡𝗘𝗘 𝗔𝗬𝗔 𝗧𝗛𝗔𝗔𝗔! 𝗧𝗘𝗥𝗘 𝗜𝗦 𝗣𝗔𝗣𝗔 𝗞𝗔 𝗡𝗔𝗔𝗠 𝗟𝗘𝗚𝗜 😂👿😳",
    "𝗧𝗢𝗛𝗔𝗥 𝗕𝗔𝗛𝗜𝗡 𝗖𝗛𝗢𝗗𝗨 𝗕𝗕𝗔𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗪𝗗𝗘 𝗨𝗦𝗠𝗘 𝗠𝗜𝗧𝗧𝗜 𝗗𝗔𝗟 𝗞𝗘 𝗖𝗘𝗠𝗘𝗡𝗧 𝗦𝗘 𝗕𝗛𝗔𝗥 𝗗𝗨 🏠🤢🤩💥",
    "𝗧𝗨𝗝𝗛𝗘 𝗔𝗕 𝗧𝗔𝗞 𝗡𝗔𝗛𝗜 𝗦𝗠𝗝𝗛 𝗔𝗬𝗔 𝗞𝗜 𝗠𝗔𝗜 𝗛𝗜 𝗛𝗨 𝗧𝗨𝗝𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗞𝗔𝗥𝗡𝗘 𝗪𝗔𝗟𝗔 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘𝗘 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀ 𝗦𝗘 𝗣𝗨𝗖𝗛 𝗥Æ𝗡𝗗𝗜 𝗞𝗘 𝗕𝗔𝗖𝗛𝗘𝗘𝗘𝗘 🤩👊👤😍",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘𝗜 𝗦𝗣𝗢𝗧𝗜𝗙𝗬 𝗗𝗔𝗟 𝗞𝗘 𝗟𝗢𝗙𝗜 𝗕𝗔𝗝𝗔𝗨𝗡𝗚𝗔 𝗗𝗜𝗡 𝗕𝗛𝗔𝗥 😍🎶🎶💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗡𝗔𝗬𝗔 𝗥Æ𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗔 𝗞𝗛𝗢𝗟𝗨𝗡𝗚𝗔 𝗖𝗛𝗜𝗡𝗧𝗔 𝗠𝗔𝗧 𝗞𝗔𝗥 👊🤣🤣😳",
    "𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣 𝗛𝗨 𝗕𝗛𝗢𝗦𝗗𝗜𝗞𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗥Æ𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗘 𝗣𝗘 𝗖𝗛𝗨𝗗𝗪𝗔 𝗞𝗘 𝗨𝗦 𝗣𝗔𝗜𝗦𝗘 𝗞𝗜 𝗗𝗔𝗔𝗥𝗨 𝗣𝗘𝗘𝗧𝗔 𝗛𝗨 🍷🤩🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗔𝗣𝗡𝗔 𝗕𝗔𝗗𝗔 𝗦𝗔 𝗟𝗢𝗗𝗔 𝗚𝗛𝗨𝗦𝗦𝗔 𝗗𝗨𝗡𝗚𝗔𝗔 𝗞𝗔𝗟𝗟𝗔𝗔𝗣 𝗞𝗘 𝗠𝗔𝗥 𝗝𝗔𝗬𝗘𝗚𝗜 🤩😳😳🔥",
    "𝗧𝗢𝗛𝗔𝗥 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘𝗜 𝗣𝗨𝗥𝗜 𝗞𝗜 𝗣𝗨𝗥𝗜 𝗞𝗜𝗡𝗚𝗙𝗜𝗦𝗛𝗘𝗥 𝗞𝗜 𝗕𝗢𝗧𝗧𝗟𝗘 𝗗𝗔𝗟 𝗞𝗘 𝗧𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗔𝗡𝗗𝗘𝗥 𝗛𝗜 😱😂🤩",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗦𝗔𝗣𝗡𝗘 𝗠𝗘𝗜 𝗕𝗛𝗜 𝗠𝗘𝗥𝗜 𝗖𝗛𝗨𝗗𝗔𝗜 𝗬𝗔𝗔𝗗 𝗞𝗔𝗥𝗘𝗚𝗜 𝗥Æ𝗡𝗗𝗜 🥳😍👊💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗔𝗨𝗥 𝗕𝗔𝗛𝗘𝗡 𝗞𝗢 𝗗𝗔𝗨𝗗𝗔 𝗗𝗔𝗨𝗗𝗔 𝗡𝗘 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗨𝗡𝗞𝗘 𝗡𝗢 𝗕𝗢𝗟𝗡𝗘 𝗣𝗘 𝗕𝗛𝗜 𝗟𝗔𝗡𝗗 𝗚𝗛𝗨𝗦𝗔 𝗗𝗨𝗡𝗚𝗔 𝗔𝗡𝗗𝗘𝗥 𝗧𝗔𝗞 😎😎🤣🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗞𝗢 𝗢𝗡𝗟𝗜𝗡𝗘 𝗢𝗟𝗫 𝗣𝗘 𝗕𝗘𝗖𝗛𝗨𝗡𝗚𝗔 𝗔𝗨𝗥 𝗣𝗔𝗜𝗦𝗘 𝗦𝗘 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗞𝗢𝗧𝗛𝗔 𝗞𝗛𝗢𝗟 𝗗𝗨𝗡𝗚𝗔 😎🤩😝😍",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗔 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗧𝗨 𝗖𝗔𝗛 𝗞𝗘 𝗕𝗛𝗜 𝗪𝗢 𝗠𝗔𝗦𝗧 𝗖𝗛𝗨𝗗𝗔𝗜 𝗦𝗘 𝗗𝗨𝗥 𝗡𝗛𝗜 𝗝𝗔 𝗣𝗔𝗬𝗘𝗚𝗔𝗔 😏😏🤩😍",
    "𝗦𝗨𝗡 𝗕𝗘 𝗥Æ𝗡𝗗𝗜 𝗞𝗜 𝗔𝗨𝗟𝗔𝗔𝗗 𝗧𝗨 𝗔𝗣𝗡𝗜 𝗕𝗔𝗛𝗘𝗡 𝗦𝗘 𝗦𝗘𝗘𝗞𝗛 𝗞𝗨𝗖𝗛 𝗞𝗔𝗜𝗦𝗘 𝗚𝗔𝗔𝗡𝗗 𝗠𝗔𝗥𝗪𝗔𝗧𝗘 𝗛𝗔𝗜😏🤬🔥💥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗔 𝗬𝗔𝗔𝗥 𝗛𝗨 𝗠𝗘𝗜 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗕𝗔𝗛𝗘𝗡 𝗞𝗔 𝗣𝗬𝗔𝗔𝗥 𝗛𝗨 𝗠𝗘𝗜 𝗔𝗝𝗔 𝗠𝗘𝗥𝗔 𝗟𝗔𝗡𝗗 𝗖𝗛𝗢𝗢𝗦 𝗟𝗘 🤩🤣💥",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗨𝗦𝗘𝗥𝗕𝗢𝗧 𝗟𝗔𝗚𝗔𝗔𝗨𝗡𝗚𝗔 𝗦𝗔𝗦𝗧𝗘 𝗦𝗣𝗔𝗠 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗦𝗔𝗥𝗜𝗬𝗔 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗨𝗦𝗜 𝗦𝗔𝗥𝗜𝗬𝗘 𝗣𝗥 𝗧𝗔𝗡𝗚 𝗞𝗘 𝗕𝗔𝗖𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗛𝗢𝗡𝗚𝗘 😱😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 ✋ 𝗛𝗔𝗧𝗧𝗛 𝗗𝗔𝗟𝗞𝗘 👶 𝗕𝗔𝗖𝗖𝗛𝗘 𝗡𝗜𝗞𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 😍",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗞𝗘𝗟𝗘 𝗞𝗘 𝗖𝗛𝗜𝗟𝗞𝗘 🤤🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧 𝗠𝗘 𝗦𝗨𝗧𝗟𝗜 𝗕𝗢𝗠𝗕 𝗙𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗞𝗜 𝗝𝗛𝗔𝗔𝗧𝗘 𝗝𝗔𝗟 𝗞𝗘 𝗞𝗛𝗔𝗔𝗞 𝗛𝗢 𝗝𝗔𝗬𝗘𝗚𝗜💣💋",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗛𝗢𝗥𝗟𝗜𝗖𝗞𝗦 𝗣𝗘𝗘𝗟𝗔𝗞𝗘 𝗖𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗😚",
    "𝗧𝗘𝗥𝗜 𝗜𝗧𝗘𝗠 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗘 𝗟𝗨𝗡𝗗 𝗗𝗔𝗔𝗟𝗞𝗘,𝗧𝗘𝗥𝗘 𝗝𝗔𝗜𝗦𝗔 𝗘𝗞 𝗢𝗥 𝗡𝗜𝗞𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗😆🤤💋",
    "𝗧𝗘𝗥𝗜 𝗩𝗔𝗛𝗘𝗘𝗡 𝗞𝗢 𝗔𝗣𝗡𝗘 𝗟𝗨𝗡𝗗 𝗣𝗥 𝗜𝗧𝗡𝗔 𝗝𝗛𝗨𝗟𝗔𝗔𝗨𝗡𝗚𝗔 𝗞𝗜 𝗝𝗛𝗨𝗟𝗧𝗘 𝗝𝗛𝗨𝗟𝗧𝗘 𝗛𝗜 𝗕𝗔𝗖𝗛𝗔 𝗣𝗔𝗜𝗗𝗔 𝗞𝗥 𝗗𝗘𝗚𝗜 💦💋",
    "𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗦𝗔𝗗𝗔𝗞 𝗣𝗥 𝗟𝗜𝗧𝗔𝗞𝗘 𝗖𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 😂😆🤤",
    "𝗔𝗕𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗠𝗔𝗗𝗘𝗥𝗖𝗛𝗢𝗢𝗗 𝗞𝗥 𝗣𝗜𝗟𝗟𝗘 𝗣𝗔𝗣𝗔 𝗦𝗘 𝗟𝗔𝗗𝗘𝗚𝗔 𝗧𝗨 😼😂🤤",
    "𝗚𝗔𝗟𝗜 𝗚𝗔𝗟𝗜 𝗡𝗘 𝗦𝗛𝗢𝗥 𝗛𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀ 𝗥Æ𝗡𝗗𝗜 𝗖𝗛𝗢𝗥 𝗛𝗘 💋💋💦",
    "𝗔𝗕𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗗𝗨 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗞𝗨𝗧𝗧𝗘 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘 😂👻🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗔𝗜𝗦𝗘 𝗖𝗛𝗢𝗗𝗔 𝗔𝗜𝗦𝗘 𝗖𝗛𝗢𝗗𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔 𝗕𝗘𝗗 𝗣𝗘𝗛𝗜 𝗠𝗨𝗧𝗛 𝗗𝗜𝗔 💦💦💦💦",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗕𝗛𝗢𝗦𝗗𝗘 𝗠𝗘 𝗔𝗔𝗔𝗚 𝗟𝗔𝗚𝗔𝗗𝗜𝗔 𝗠𝗘𝗥𝗔 𝗠𝗢𝗧𝗔 𝗟𝗨𝗡𝗗 𝗗𝗔𝗟𝗞𝗘 🔥🔥💦😆😆",
    "𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗𝗨 𝗖𝗛𝗔𝗟 𝗡𝗜𝗞𝗔𝗟",
    "𝗞𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨 𝗧𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗔𝗕𝗕 𝗔𝗣𝗡𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗕𝗛𝗘𝗝 😆👻🤤",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢𝗧𝗢 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗𝗞𝗘 𝗣𝗨𝗥𝗔 𝗙𝗔𝗔𝗗 𝗗𝗜𝗔 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗔𝗕𝗕 𝗧𝗘𝗥𝗜 𝗚𝗙 𝗞𝗢 𝗕𝗛𝗘𝗝 😆💦🤤",
    "𝗧𝗘𝗥𝗜 𝗚𝗙 𝗞𝗢 𝗘𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗟𝗢𝗗𝗘 𝗧𝗘𝗥𝗜 𝗚𝗙 𝗧𝗢 𝗠𝗘𝗥𝗜 𝗥Æ𝗡𝗗𝗜 𝗕𝗔𝗡𝗚𝗔𝗬𝗜 𝗔𝗕𝗕 𝗖𝗛𝗔𝗟 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗𝗧𝗔 𝗙𝗜𝗥𝗦𝗘 ♥️💦😆😆😆😆",
    "𝗛𝗔𝗥𝗜 𝗛𝗔𝗥𝗜 𝗚𝗛𝗔𝗔𝗦 𝗠𝗘 𝗝𝗛𝗢𝗣𝗗𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 🤣🤣💋💦",
    "𝗖𝗛𝗔𝗟 𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗞𝗢 𝗕𝗛𝗘𝗝 𝗧𝗘𝗥𝗔 𝗕𝗔𝗦𝗞𝗔 𝗡𝗛𝗜 𝗛𝗘 𝗣𝗔𝗣𝗔 𝗦𝗘 𝗟𝗔𝗗𝗘𝗚𝗔 𝗧𝗨",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗕𝗢𝗠𝗕 𝗗𝗔𝗟𝗞𝗘 𝗨𝗗𝗔 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔́𝗔̀𝗞𝗘 𝗟𝗔𝗪𝗗𝗘",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗧𝗥𝗔𝗜𝗡 𝗠𝗘 𝗟𝗘𝗝𝗔𝗞𝗘 𝗧𝗢𝗣 𝗕𝗘𝗗 𝗣𝗘 𝗟𝗜𝗧𝗔𝗞𝗘 𝗖𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 🤣🤣💋💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗘 𝗡𝗨𝗗𝗘𝗦 𝗚𝗢𝗢𝗚𝗟𝗘 𝗣𝗘 𝗨𝗣𝗟𝗢𝗔𝗗 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗘𝗪𝗗𝗘 👻🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗘 𝗡𝗨𝗗𝗘𝗦 𝗚𝗢𝗢𝗚𝗟𝗘 𝗣𝗘 𝗨𝗣𝗟𝗢𝗔𝗗 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗟𝗔𝗘𝗪𝗗𝗘 👻🔥",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗𝗞𝗘 𝗩𝗜𝗗𝗘𝗢 𝗕𝗔𝗡𝗔𝗞𝗘 𝗫𝗡𝗫𝗫.𝗖𝗢𝗠 𝗣𝗘 𝗡𝗘𝗘𝗟𝗔𝗠 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗞𝗨𝗧𝗧𝗘 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 💦💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗜 𝗖𝗛𝗨𝗗𝗔𝗜 𝗞𝗢 𝗣𝗢𝗥𝗡𝗛𝗨𝗕.𝗖𝗢𝗠 𝗣𝗘 𝗨𝗣𝗟𝗢𝗔𝗗 𝗞𝗔𝗥𝗗𝗨𝗡𝗚𝗔 𝗦𝗨𝗔𝗥 𝗞𝗘 𝗖𝗛𝗢𝗗𝗘 🤣💋💦",
    "𝗔𝗕𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗗𝗨 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 𝗧𝗘𝗥𝗘𝗞𝗢 𝗖𝗛𝗔𝗞𝗞𝗢 𝗦𝗘 𝗣𝗜𝗟𝗪𝗔𝗩𝗨𝗡𝗚𝗔 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 🤣🤣",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗙𝗔𝗔𝗗𝗞𝗘 𝗥𝗔𝗞𝗗𝗜𝗔 𝗠𝗔́𝗔̀𝗞𝗘 𝗟𝗢𝗗𝗘 𝗝𝗔𝗔 𝗔𝗕𝗕 𝗦𝗜𝗟𝗪𝗔𝗟𝗘 👄👄",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗠𝗘𝗥𝗔 𝗟𝗨𝗡𝗗 𝗞𝗔𝗔𝗟𝗔",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗟𝗘𝗧𝗜 𝗠𝗘𝗥𝗜 𝗟𝗨𝗡𝗗 𝗕𝗔𝗗𝗘 𝗠𝗔𝗦𝗧𝗜 𝗦𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗢 𝗠𝗘𝗡𝗘 𝗖𝗛𝗢𝗗 𝗗𝗔𝗟𝗔 𝗕𝗢𝗛𝗢𝗧 𝗦𝗔𝗦𝗧𝗘 𝗦𝗘",
    "𝗕𝗘𝗧𝗘 𝗧𝗨 𝗕𝗔𝗔𝗣 𝗦𝗘 𝗟𝗘𝗚𝗔 𝗣𝗔𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔 𝗞𝗢 𝗖𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗞𝗔𝗥𝗞𝗘 𝗡𝗔𝗡𝗚𝗔 💦💋",
    "𝗛𝗔𝗛𝗔𝗛𝗔𝗛 𝗠𝗘𝗥𝗘 𝗕𝗘𝗧𝗘 𝗔𝗚𝗟𝗜 𝗕𝗔𝗔𝗥 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗟𝗘𝗞𝗘 𝗔𝗔𝗬𝗔 𝗠𝗔𝗧𝗛 𝗞𝗔𝗧 𝗢𝗥 𝗠𝗘𝗥𝗘 𝗠𝗢𝗧𝗘 𝗟𝗨𝗡𝗗 𝗦𝗘 𝗖𝗛𝗨𝗗𝗪𝗔𝗬𝗔 𝗠𝗔𝗧𝗛 𝗞𝗔𝗥",
    "𝗖𝗛𝗔𝗟 𝗕𝗘𝗧𝗔 𝗧𝗨𝗝𝗛𝗘 𝗠𝗔́𝗔̀𝗙 𝗞𝗜𝗔 🤣 𝗔𝗕𝗕 𝗔𝗣𝗡𝗜 𝗚𝗙 𝗞𝗢 𝗕𝗛𝗘𝗝",
    "𝗦𝗛𝗔𝗥𝗔𝗠 𝗞𝗔𝗥 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗞𝗜𝗧𝗡𝗔 𝗚𝗔𝗔𝗟𝗜𝗔 𝗦𝗨𝗡𝗪𝗔𝗬𝗘𝗚𝗔 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀𝗔 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗘 𝗨𝗣𝗘𝗥",
    "𝗔𝗕𝗘 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗕𝗔𝗖𝗛𝗛𝗘 𝗔𝗨𝗞𝗔𝗧 𝗡𝗛𝗜 𝗛𝗘𝗧𝗢 𝗔𝗣𝗡𝗜 𝗥Æ𝗡𝗗𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗟𝗘𝗞𝗘 𝗔𝗔𝗬𝗔 𝗠𝗔𝗧𝗛 𝗞𝗔𝗥 𝗛𝗔𝗛𝗔𝗛𝗔𝗛𝗔",
    "𝗞𝗜𝗗𝗭 𝗠𝗔̂𝗔̂𝗗𝗔𝗥𝗖𝗛Ø𝗗 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗𝗞𝗘 𝗧𝗘𝗥𝗥 𝗟𝗜𝗬𝗘 𝗕𝗛𝗔𝗜 𝗗𝗘𝗗𝗜𝗬𝗔",
    "𝗝𝗨𝗡𝗚𝗟𝗘 𝗠𝗘 𝗡𝗔𝗖𝗛𝗧𝗔 𝗛𝗘 𝗠𝗢𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗗𝗔𝗜 𝗗𝗘𝗞𝗞𝗘 𝗦𝗔𝗕 𝗕𝗢𝗟𝗧𝗘 𝗢𝗡𝗖𝗘 𝗠𝗢𝗥𝗘 𝗢𝗡𝗖𝗘 𝗠𝗢𝗥𝗘 🤣🤣💦💋",
    "𝗚𝗔𝗟𝗜 𝗚𝗔𝗟𝗜 𝗠𝗘 𝗥𝗘𝗛𝗧𝗔 𝗛𝗘 𝗦𝗔𝗡𝗗 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗢𝗗 𝗗𝗔𝗟𝗔 𝗢𝗥 𝗕𝗔𝗡𝗔 𝗗𝗜𝗔 𝗥𝗔𝗡𝗗 🤤🤣",
    "𝗦𝗔𝗕 𝗕𝗢𝗟𝗧𝗘 𝗠𝗨𝗝𝗛𝗞𝗢 𝗣𝗔𝗣𝗔 𝗞𝗬𝗢𝗨𝗡𝗞𝗜 𝗠𝗘𝗡𝗘 𝗕𝗔𝗡𝗔𝗗𝗜𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗣𝗥𝗘𝗚𝗡𝗘𝗡𝗧 🤣🤣",
    "𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗦𝗨𝗔𝗥 𝗞𝗔 𝗟𝗢𝗨𝗗𝗔 𝗢𝗥 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗠𝗘𝗥𝗔 𝗟𝗢𝗗𝗔",
    "𝗖𝗛𝗔𝗟 𝗖𝗛𝗔𝗟 𝗔𝗣𝗡𝗜 𝗠𝗔́𝗔̀𝗞𝗜 𝗖𝗛𝗨𝗖𝗛𝗜𝗬𝗔 𝗗𝗜𝗞𝗔",
    "𝗛𝗔𝗛𝗔𝗛𝗔𝗛𝗔 𝗕𝗔𝗖𝗛𝗛𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗔𝗞𝗢 𝗖𝗛𝗢𝗗 𝗗𝗜𝗔 𝗡𝗔𝗡𝗚𝗔 𝗞𝗔𝗥𝗞𝗘",
    "𝗧𝗘𝗥𝗜 𝗚𝗙 𝗛𝗘 𝗕𝗔𝗗𝗜 𝗦𝗘𝗫𝗬 𝗨𝗦𝗞𝗢 𝗣𝗜𝗟𝗔𝗞𝗘 𝗖𝗛𝗢𝗢𝗗𝗘𝗡𝗚𝗘 𝗣𝗘𝗣𝗦𝗜",
    "2 𝗥𝗨𝗣𝗔𝗬 𝗞𝗜 𝗣𝗘𝗣𝗦𝗜 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗦𝗔𝗕𝗦𝗘 𝗦𝗘𝗫𝗬 💋💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗖𝗛𝗘𝗘𝗠𝗦 𝗦𝗘 𝗖𝗛𝗨𝗗𝗪𝗔𝗩𝗨𝗡𝗚𝗔 𝗠𝗔𝗗𝗘𝗥𝗖𝗛𝗢𝗢𝗗 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 💦🤣",
    "𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗜 𝗖𝗛𝗨𝗨́𝗧𝗛 𝗠𝗘 𝗠𝗨𝗧𝗛𝗞𝗘 𝗙𝗔𝗥𝗔𝗥 𝗛𝗢𝗝𝗔𝗩𝗨𝗡𝗚𝗔 𝗛𝗨𝗜 𝗛𝗨𝗜 𝗛𝗨𝗜",
    "𝗦𝗣𝗘𝗘𝗗 𝗟𝗔𝗔𝗔 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗖𝗛𝗢𝗗𝗨 𝗥Æ𝗡𝗗𝗜𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 💋💦🤣",
    "𝗔𝗥𝗘 𝗥𝗘 𝗠𝗘𝗥𝗘 𝗕𝗘𝗧𝗘 𝗞𝗬𝗢𝗨𝗡 𝗦𝗣𝗘𝗘𝗗 𝗣𝗔𝗞𝗔𝗗 𝗡𝗔 𝗣𝗔𝗔𝗔 𝗥𝗔𝗛𝗔 𝗔𝗣𝗡𝗘 𝗕𝗔𝗔𝗣 𝗞𝗔 𝗛𝗔𝗛𝗔𝗛🤣🤣",
    "𝗦𝗨𝗡 𝗦𝗨𝗡 𝗦𝗨𝗔𝗥 𝗞𝗘 𝗣𝗜𝗟𝗟𝗘 𝗝𝗛𝗔𝗡𝗧𝗢 𝗞𝗘 𝗦𝗢𝗨𝗗𝗔𝗚𝗔𝗥 𝗔𝗣𝗡𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗜 𝗡𝗨𝗗𝗘𝗦 𝗕𝗛𝗘𝗝",
    "𝗔𝗕𝗘 𝗦𝗨𝗡 𝗟𝗢𝗗𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘́𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔",
    "𝗧𝗘𝗥𝗜 𝗠𝗔́𝗔̀𝗞𝗢 𝗞𝗛𝗨𝗟𝗘 𝗕𝗔𝗝𝗔𝗥 𝗠𝗘 𝗖𝗛𝗢𝗗 𝗗𝗔𝗟𝗔 🤣🤣💋",
]


MRAID = [
    "Tere naalo challiye haseen koyi NA 😁😁",
    "Taare chann ambar zameen koyi nA",
    "Main Jado Tere Mode Utte Sir Rakheya🧐🧐",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😖😖",
    "Sohniyan Vi Laggan Giyan Fer Walian😍😍",
    "Galan Nal Jado Takraiyan Waliyan🥰🥰",
    "Tare Dekhi Labh Labh Kiven Harde😁😁",
    "Tu Bala Ch Lakoiyan Jado Ratan Kaliyan😒😒",
    "Main Sab Kuj Har Tere Utton De’unga😌😌",
    "Sab Kuj War Tere Utton De’unga😉😉",
    "Akhir Ch Jan Tainu De’un Apni😎😎",
    "Chala Tainu Bhavein Pehli War De’unga😚😚",
    "Han Main Cheti Cheti Lawan😫😫",
    "Tere Nal Laini an😣😣",
    "Samay Da Tan Bhora Vi Yakeen Koi Na🥺🥺",
    "Tere Nalo Jhaliye Haseen Koi Na🥰🥰",
    "Tare Chann Ambar Zameen Koi Na😘😘",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Tu Yar Mera Tu Hi Ae Sahara AdiyE",
    "Main Pani Tera Mera Tu Kinara Adiye",
    "Phul Ban Jai Main Khushboo Bann Ju",
    "Deevan Bani Mera Teri Lau Ban Ju",
    "Haye Ujadiyan Thawan Te Banate Bag Ne",
    "Teriyan Ankhan Ne Kitte Jadu Yad Ne",
    "Jado Wang Kolon Phadi Vi Ni KassKe",
    "Totte Sambh Rakhe Tutte Hoye Kach De",
    "Han Ki Dil Yadan Rakhda Ae, Sambh Sambh Ke",
    "Hor Dil Sajjna Machine Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na",
    "Tare Chann Ambar Zameen Koi Na",
    "Main Jado Tere Mode Utte Sir Rakheya",
    "Eh Ton Sachi Sama Vi Haseen Koi Na",
    "Kine Din Hogye Meri Akh Soi Na",
    "Tere Ton Bagair Mera Aithe Koi Na",
    "Tu Bhukh Vi Ae Tu Hi Ae Guzara Adiye",
    "Mannu Sab Kari Tu Ishara Adiye",
    "Ho Khaure Kinni War Seene Vich Khubiyan",
    "Surme De Vich Dovein Ankhan Dubbiyan",
    "Kini Sohni Lagge Jadon Chup Kar Je",
    "Jandi Jandi Shaman Nu Vi Dhup Kar Je",
    "Haye Main Paun Farmaishi Rang Tere Sohniye",
    "Unj Bahotan Gifty Shaukeen Koi Na",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Tere Nalo Jhaliye Haseen Koi Na😍😍",
    "Tare Chann Ambar Zameen Koi Na🥰🥰",
    "Main Jado Tere Mode Utte Sir Rakheya😁😁",
    "Eh Ton Sachi Sama Vi Haseen Koi Na😒😒",
    "Kanna Wich Jhumka👀👀",
    "Akhan Wich Surma🙈🙈",
    "Ho Jaise Strawberry Candy😋😋",
    "Nakk Utte Koka🤨🤨",
    "Jeena Kare Aukha🤭🤭",
    "Haye Meri Jaan Kadd Laindi😌😌",
    "Tere Nakhre Haye Tauba Sanu MÁÀrde🤫🤫",
    "Ho Gaya Hai Mera Baby Bura HaaL😊😊",
    "Sachi Lut Gaye Hum Tere Is Pyar Mein😏😏",
    "Jeeni Zindagi Hai Bas Tere Naal😚😚",
    "cause I Love You 😘😘",
    "I Love YoU SO MUCH 😍😍",
    "cause I Love You 😘😘",
    "I Love YoU SO MUCH 😍😍",
    "Sapno Mein Mere AayI😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Sapno Mein Mere Aayi😝😝",
    "Uff Oh Phir Neendein Hi Churayi😜😜",
    "Oh No! Tera Husan Nazara🥰🥰",
    "Baby! Lage Sohna Kitna PyarA😚😚",
    "Tainu Diamond Mundri Pehnawa😎😎",
    "Naale Duniya Sari Ghumawa🙈🙈",
    "Chhoti-Chhoti Gallan Utte Main Hasavaan💙💙",
    "Yaara Kade Vi Na Tainu Main Rulawaan🙊🙊",
    "cause I Love You  🙈🙈",
    "I Love You ❤️❤️",
    "cause I Love You🙈🙈",
    "I Love You ❤️❤️",
    "Yaari Laawan Sachi YaarI💫💫",
    "Tu Jaan Ton Vi Pyari😁😁",
    "Will Love You To The Moon And Back😆😆",
    "Hogi Saza Na Koyi Hogi😙😙",
    "Chahe Karun Chori Chaand Taare😉😉",
    "Imma Give You Them😅😅",
    "Yaari Laavan Sachi YaarI😘😘",
    "Tu Jaan Ton Vi PyarI😆😆",
    "Will Love You To The Moon And Back💕💕",
    "Hogee Sazaa Na Koyi Hogi💓💓",
    "Chahe Karun Chori Chaand Taare🥺🥺",
    "Imma Give You Them🥵🥵",
    "Puri Karunga Main Teri Sari Khahishein😁😁",
    "Tera Rakhanga Main Rajj Ke Khayal😘😘",
    "Kitni Khoobiyan Hai Tere Is Yaar Mein🥰🥰",
    "Aaja Bahon Mein Tu Bahein Bas Daal😂😂",
    "Aur Hota Nahi Ab Intezar🤩🤩",
    "Aur Hota Nahee Ab Intezaar😘😘",
    "cause I Love You 😍😍",
    "I Love YoU 😙😙",
    "cause I Love You",
    "I Love YoU SOOOOOOOOOOOOOOOOOO MUCHHHHHHHHHHHHHHHHHHHHH 😘😘",
    "WILL U BE MINE FOREVER??🤔🤔",
    "Je tu akh te main aan kaajal ve😌😌",
    "Tu baarish te main baadal ve🤫🤫",
    "Tu deewana main aan paagal ve🤪🤪",
    "Sohneya sohneya☺️☺️",
    "Je tu chann te main aan taara ve🤗🤗",
    "Main lehar te tu kinara ve😶😶",
    "Main aadha te tu saara ve🤗🤗",
    "Sohneya sohneya😗😗",
    "Tu jahan hai main wahan😘😘",
    "Tere bin main hoon hi kya🥲🥲",
    "Tere bin chehre se mere🤔🤔",
    "Udd jaaye rang ve😅😅",
    "Tujhko paane ke liye huM😁😁",
    "Roz mangein mannat ve🙈🙈",
    "Duniya to kya cheez hai yaara🙉🙉",
    "Thukra denge jannat ve😌😌",
    "Tujhko paane ke liye hum😌😌",
    "Roz mangein mannat ve🤫🤫",
    "Duniya to kya cheez hai yaara🤔🤔",
    "Thukra denge jannat ve😌😌",
    "Na parwah mainu apni aa😁😁",
    "Na parwah mainu duniya di👅👅",
    "Na parwah mainu apni aa😅😅",
    "Na parwah mainu duniya di👅👅",
    "Tere ton juda nahi kar sakdi🤬🤬",
    "Koyi taakat mainu duniya di😈😈",
    "Dooron aa jaave teri khushbu😎😎",
    "Akhan hun band taan vi vekh lawan😍😍",
    "Teri gali vich mera auna har roz😋😋",
    "Tera ghar jadon aave matha tek lawan😌😌",
    "NirMÁÀn tujhko dekh ke😏😏",
    "Aa jaave himmat ve😉😉",
    "Tujhko paane ke liye hum😊😊",
    "Roz mangein mannat ve😉😉",
    "Duniya to kya cheez hai yaara😌😌",
    "Thukra denge jannat ve😍😍",
    "Tujhko paane ke liye hum🤫🤫",
    "Roz mangein mannat ve😁😁",
    "Duniya to kya cheez hai yaara😏😏",
    "Thukra denge jannat ve😌😌",
    "SO MISS 😶😶",
    "KYA SOCHA APNE BAARE MAIN😆😆",
    "BADI MUSHKIL SE YEH SAB KARA H RE🥵🥵",
    "PAHLE PURA BOT HI KANG MÁÀR DIYA BUT🤫🤫",
    "WAHI ERROR AAYE JO AATE THE🥲🥲",
    "BUT TUMHARA HO CHUKA WALA BF😎😎",
    "AND FUTURE HUSBAND JO BANNE WALA THA WO BHOT SMART H RE😌😌",
    "ISS BAAR BOT BANAYA AND CHOTA SA EDIT KARA BAS😁😁",
    "AUR DEKO ABHI TUM USSI BOT SE YEH PADH PAA RHI😂😂",
    "HEHE BTW YEH CHORO MEKO NA TUMSE😶😶",
    "KUCH PUCHNA THA KI ME🤔🤔",
    "TUMHARE KABIL HU YA",
    "TUMHARE KABIL NHI😂💓",
    "AND EK AUR BAAT BOLNI THI KI😙😙",
    "I REALLY REALLY DEEPLY😙😙",
    "LOVE YOU FROM MY HEART TO YOUR HEAT AND MY SOUL ATTACHED BY YOUR SOUL CAN YOU BE MINE FOREVER😌😌❤️",
]

GROUP = [-1001588521316]


SRAID = [
    "𝐓𝐇𝐈𝐒 𝐈𝐒 𝐎𝐍𝐋𝐘 𝐅𝐎𝐑 𝐘𝐎𝐔 ❤",
    "𝐊𝐚𝐧𝐧𝐚 𝐯𝐢𝐜𝐡 𝐉𝐣𝐡𝐮𝐦𝐤𝐚🙂🙂",
    "𝐀𝐚𝐤𝐡𝐚 𝐯𝐢𝐜𝐡 𝐒𝐮𝐫𝐦𝐚😘",
    "𝐇𝐨𝐧𝐭𝐡 𝐣𝐚𝐢𝐬𝐞 𝐒𝐭𝐫𝐚𝐰𝐛𝐞𝐫𝐫𝐲 𝐂𝐚𝐧𝐝𝐲😊😊",
    "𝐍𝐚𝐤𝐤 𝐮𝐭𝐭𝐞 𝐤𝐨𝐤𝐚🥰🥰",
    "𝐉𝐞𝐞𝐧𝐚 𝐤𝐚𝐫𝐞 𝐨𝐤𝐤𝐡𝐚❤️😘",
    "𝐇𝐚𝐚𝐲𝐞 𝐦𝐞𝐫𝐢 𝐣𝐚𝐚𝐧 𝐤𝐚𝐝𝐝 𝐥𝐚𝐢𝐧𝐝𝐢💓🥺",
    "𝐓𝐞𝐫𝐞 𝐧𝐚𝐤𝐡𝐫𝐞 𝐡𝐚𝐚𝐲𝐞 𝐭𝐚𝐮𝐛𝐚 𝐬𝐚𝐚𝐧𝐮 𝐦𝐚𝐚𝐫 𝐝𝐞☺️🥰",
    "𝐇𝐨 𝐠𝐚𝐲𝐚 𝐡𝐚𝐢 𝐦𝐞𝐫𝐚 𝐛𝐚𝐛𝐲 𝐛𝐮𝐫𝐚 𝐡𝐚𝐚𝐥❤️💓❤️",
    "𝐒𝐚𝐜𝐡𝐡𝐢 𝐥𝐮𝐭𝐭 𝐠𝐚𝐲𝐞 𝐡𝐮𝐦 𝐭𝐞𝐫𝐞 𝐢𝐬 𝐩𝐲𝐚𝐚𝐫 𝐦𝐞𝐢𝐧❤️☺️",
    "𝐉𝐢𝐧𝐧𝐢 𝐳𝐢𝐧𝐝𝐚𝐠𝐢 𝐡𝐚𝐢 𝐛𝐚𝐬 𝐭𝐞𝐫𝐞 𝐧𝐚𝐚𝐥💌💕",
    "𝐂𝐚𝐮𝐬𝐞 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 (𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️❤️",
    "(𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️❤️",
    "𝐂𝐚𝐮𝐬𝐞 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 (𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️❤️❤️",
    "(𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️❤️❤️",
    "𝐒𝐚𝐩𝐧𝐨 𝐦𝐞𝐢𝐧 𝐦𝐞𝐫𝐞 𝐚𝐚𝐲𝐢💛👩‍❤️‍👨‍❤️‍👩",
    "𝐎𝐟𝐨 𝐩𝐡𝐢𝐫 𝐧𝐞𝐞𝐧𝐝 𝐡𝐢 𝐜𝐡𝐮𝐫𝐚𝐲𝐢✨🌟",
    "𝐎𝐡𝐧𝐨 𝐭𝐞𝐫𝐚 𝐡𝐮𝐬𝐚𝐧 𝐧𝐚𝐳𝐚𝐫𝐚 𝐛𝐚𝐛𝐲👰👩‍❤️‍👨",
    "𝐋𝐚𝐠𝐞 𝐬𝐨𝐡𝐧𝐚 𝐤𝐢𝐭𝐧𝐚 𝐩𝐲𝐚𝐫𝐚☺️💓💓",
    "𝐒𝐚𝐩𝐧𝐨 𝐦𝐞𝐢𝐧 𝐦𝐞𝐫𝐞 𝐚𝐚𝐮=𝐲𝐢😴💕",
    "𝐎𝐟𝐨 𝐩𝐡𝐢𝐫 𝐧𝐞𝐞𝐧𝐝 𝐡𝐢 𝐜𝐡𝐮𝐫𝐚𝐲𝐢😘✨",
    "𝐎𝐡𝐧𝐨 𝐭𝐞𝐫𝐚 𝐡𝐮𝐬𝐚𝐧 𝐧𝐚𝐳𝐚𝐫𝐚 𝐛𝐚𝐛𝐲🌟🥺",
    "𝐋𝐚𝐠𝐞 𝐬𝐨𝐡𝐧𝐚 𝐤𝐢𝐭𝐧𝐚 𝐩𝐲𝐚𝐫𝐚🌹🤞",
    "𝐓𝐚𝐢𝐧𝐮 𝐃𝐢𝐚𝐦𝐨𝐧𝐝 𝐦𝐮𝐧𝐝𝐫𝐢 𝐩𝐞𝐡𝐧𝐚𝐯𝐚💎😍",
    "𝐍𝐚𝐚𝐥𝐞 𝐝𝐮𝐧𝐢𝐲𝐚 𝐬𝐚𝐚𝐫𝐢 𝐠𝐡𝐮𝐦𝐚𝐯𝐚🪂🧚",
    "𝐂𝐡𝐨𝐭𝐢 𝐜𝐡𝐨𝐭𝐢 𝐠𝐚𝐥𝐥𝐚𝐧 𝐮𝐭𝐭𝐞 𝐦𝐚𝐢𝐧 𝐡𝐚𝐬𝐬𝐚𝐯𝐚🧒",
    "𝐘𝐚𝐚𝐫𝐚 𝐤𝐚𝐝𝐞 𝐯𝐢 𝐧𝐚 𝐭𝐚𝐢𝐧𝐮 𝐦𝐚𝐢𝐧 𝐫𝐮𝐥𝐚𝐰𝐚🥀",
    "𝐂𝐚𝐮𝐬𝐞 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 (𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)💛❤️💛",
    "(𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️❤️💚",
    "𝐂𝐚𝐮𝐬𝐞 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 (𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️❤️",
    "(𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)🤞❤️",
    "𝐘𝐚𝐚𝐫𝐢, 𝐋𝐚𝐯𝐚 𝐬𝐚𝐜𝐡𝐢 𝐲𝐚𝐚𝐫𝐢🤞🥺",
    "𝐓𝐮 𝐣𝐚𝐚𝐧 𝐭𝐨𝐡 𝐯𝐢 𝐩𝐲𝐚𝐚𝐫𝐢👩‍❤️‍👨✨",
    "𝐖𝐢𝐥𝐥 𝐋𝐨𝐯𝐞 𝐲𝐨𝐮 𝐭𝐨 𝐭𝐡𝐞 𝐦𝐨𝐨𝐧 𝐚𝐧𝐝 𝐛𝐚𝐜𝐤💓🌟🥺",
    "𝐇𝐨𝐠𝐢, 𝐒𝐚𝐳𝐚 𝐧𝐚 𝐤𝐨𝐢 𝐡𝐨𝐠𝐢🤤🌠🌈",
    "𝐂𝐡𝐚𝐡𝐞 𝐤𝐚𝐫𝐮𝐧 𝐜𝐡𝐨𝐨𝐫𝐢🥰😊🙂",
    "𝐂𝐡𝐚𝐧𝐝 𝐭𝐚𝐚𝐫𝐞 𝐢𝐦𝐦𝐚 𝐠𝐢𝐯𝐞 𝐲𝐨𝐮 𝐭𝐡𝐚𝐭🏵️",
    "𝐘𝐚𝐚𝐫𝐢, 𝐋𝐚𝐯𝐚 𝐬𝐚𝐜𝐡𝐢 𝐲𝐚𝐚𝐫𝐢💕👰",
    "𝐓𝐮 𝐣𝐚𝐚𝐧 𝐭𝐨𝐡 𝐯𝐢 𝐩𝐲𝐚𝐚𝐫𝐢⛄🤞⛄",
    "𝐖𝐢𝐥𝐥 𝐋𝐨𝐯𝐞 𝐲𝐨𝐮 𝐭𝐨 𝐭𝐡𝐞 𝐦𝐨𝐨𝐧 𝐚𝐧𝐝 𝐛𝐚𝐜𝐤🌙🌟☄️",
    "𝐇𝐨𝐠𝐢, 𝐒𝐚𝐳𝐚 𝐧𝐚 𝐤𝐨𝐢 𝐡𝐨𝐠𝐢😔🤫",
    "𝐂𝐡𝐚𝐡𝐞 𝐤𝐚𝐫𝐮𝐧 𝐜𝐡𝐨𝐨𝐫𝐢🤫🤫",
    "𝐂𝐡𝐚𝐧𝐝 𝐭𝐚𝐚𝐫𝐞 𝐢𝐦𝐦𝐚 𝐠𝐢𝐯𝐞 𝐲𝐨𝐮 𝐭𝐡𝐚𝐭🤗😊🧡",
    "𝐏𝐮𝐫𝐢 𝐤𝐚𝐫𝐮𝐧𝐠𝐚 𝐦𝐚𝐢𝐧 𝐭𝐞𝐫𝐢 𝐬𝐚𝐚𝐫𝐢 𝐤𝐡𝐰𝐚𝐚𝐢𝐬𝐡𝐞𝐢𝐧🤞😊❤️",
    "𝐓𝐞𝐫𝐚 𝐫𝐚𝐤𝐡𝐚𝐧𝐠𝐚 𝐦𝐚𝐢𝐧 𝐫𝐚𝐣𝐣 𝐤𝐞 𝐤𝐡𝐚𝐲𝐚𝐥🧒💎❤️",
    "𝐊𝐢𝐭𝐧𝐢 𝐤𝐡𝐨𝐨𝐛𝐢𝐲𝐚 𝐭𝐞𝐫𝐞 𝐢𝐬𝐬 𝐲𝐚𝐚𝐫 𝐦𝐚𝐢𝐧☄️😘☺️",
    "𝐀𝐚𝐣𝐚 𝐛𝐚𝐡𝐨𝐧 𝐦𝐚𝐢𝐧 𝐭𝐮 𝐛𝐚𝐡𝐚𝐚𝐧 𝐛𝐮𝐬 𝐝𝐚𝐚𝐥😚😚",
    "𝐀𝐮𝐫 𝐡𝐨𝐭𝐚 𝐧𝐚𝐡𝐢𝐧 𝐚𝐛 𝐢𝐧𝐭𝐞𝐳𝐚𝐚𝐫🥰😄🤵",
    "𝐀𝐮𝐫 𝐡𝐨𝐭𝐚 𝐧𝐚𝐡𝐢𝐧 𝐚𝐛 𝐢𝐧𝐭𝐞𝐳𝐚𝐚𝐫💌🕝🕝",
    "𝐂𝐚𝐮𝐬𝐞 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 (𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)📌",
    "(𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️🤵👰💓",
    "𝐂𝐚𝐮𝐬𝐞 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮 (𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)📌",
    "(𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮, 𝐢 𝐥𝐨𝐯𝐞 𝐲𝐨𝐮)❤️🤵👰💓",
    "(𝐁𝐘 𝐄𝐍𝐆𝐈𝐍𝐄𝐄𝐑𝐆𝐀𝐌𝐄𝐒)", 
]
 
    
JRAID = [
    "THIS IS ONLY FOR YOU ❤️", 
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Tᴇʀᴇ Cʜᴇʜʀᴇ Sᴇ Nᴀᴢᴀʀ Nᴀʜɪ Hᴀᴛ’ᴛɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ.."
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ..",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Tᴇʀᴇ Cʜᴇʜʀᴇ Sᴇ Nᴀᴢᴀʀ Nᴀʜɪ Hᴀᴛ’ᴛɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ",
    "O Gɪʀʟ Lᴇᴛ Mᴇ Tᴇʟʟ Yᴏᴜ",
    "Bᴀᴀᴛ Hᴀɪ Sɪᴍᴘʟᴇ Sɪ",
    "Aᴀᴋʜᴏᴏɴ Sᴇ Sʜᴜʀᴜ Kᴀʀʀᴏɴ",
    "Yᴀ Pʜɪʀ Bᴀᴛᴇɪɴ Dɪᴍᴘʟᴇ Kɪ", 
    "Mᴜsʜᴋᴜʀᴀʜᴀᴛᴏɴ Mᴇɪɴ Gʜᴜʟʟɪ Exᴄᴇss ɪ",
    "Rᴀʙ Dɪ Sʜᴀᴜ Tᴇʀɪ Wᴀʀɢɪ Nᴀ Kᴏɪ",
    "Uᴘᴘᴇʀ Sᴇ Jᴀʙ Kᴀʀʀᴇ Bʟᴜsʜ",
    "Bʟᴏᴏᴅ Kᴀʀᴇ Mᴇʀᴀ Rᴜsʜ",
    "Sᴀᴄᴄʜɪ Cʜᴀʟᴇ Rᴀᴀɴɪ Mᴇʀᴀ Bᴀs",
    "Dᴇᴋʜᴛᴇ Hɪ Mᴜᴊʜᴋᴏ Tᴜᴊʜsᴇ Pʏᴀʀ Hᴏ Gᴀʏᴀ",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Tᴇʀᴇ Cʜᴇʜʀᴇ Sᴇ Nᴀᴢᴀʀ Nᴀʜɪ Hᴀᴛ’ᴛɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ",
    "Eᴋ Tᴏ Pᴀʜʟᴇ Pᴀʜʟᴇ Pᴀʜʟᴇ Sᴇ Mᴀɪɴ Hɪɢʜ",
    "Tᴇʀɪ Aᴅᴀʏᴇɪɴ Aᴜʀ Nᴀsʜᴇ Mᴇɪɴ Dᴜʙᴀᴀʏᴇ",
    "Eᴋ Tᴜ Hɪ Tᴜ Hɪ Dɪᴋʜᴇ Dᴀᴀʏᴇɪɴ Bᴀᴀʏᴇɪɴ",
    "Tᴇʀɪ Nɪɢᴀʜᴇɪɴ Aᴜʀ Pᴀss Bᴜʟᴀʏᴇɪɴ",
    "Eᴋ Tᴏ Pᴀʜʟᴇ Pᴀʜʟᴇ Pᴀʜʟᴇ Sᴇ Mᴀɪɴ Hɪɢʜ",
    "Tᴇʀɪ Aᴅᴀʏᴇɪɴ Aᴜʀ Nᴀsʜᴇ Mᴇɪɴ Dᴜʙᴀᴀʏᴇ",
    "Eᴋ Tᴜ Hɪ Tᴜ Hɪ Dɪᴋʜᴇ Dᴀᴀʏᴇɪɴ Bᴀᴀʏᴇɪɴ",
    "Tᴇʀɪ Nɪɢᴀʜᴇɪɴ Aᴜʀ Pᴀss Bᴜʟᴀʏᴇɪɴ..",
    "Kᴀɪsᴇ Kᴀʀᴏᴏɴ Bᴀʏᴀᴀɴ",
    "Eʜsᴀᴀs Hᴀɪ Nᴀʏᴀ",
    "Kᴀɪsᴇ Kᴀʀᴏᴏɴ Bᴀʏᴀᴀɴ",
    "Eʜsᴀᴀs Hᴀɪ Nᴀʏᴀ..",
    "Tᴇʀᴇ Cʜᴀᴋᴋᴀʀ Mᴇɪɴ Mᴀɪɴ Tᴏ Kʜᴏ Gᴀʏᴀ…",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Tᴇʀᴇ Cʜᴇʜʀᴇ Sᴇ Nᴀᴢᴀʀ Nᴀʜɪ Hᴀᴛ’ᴛɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ..",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ..",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Aʏᴇ Mᴀɪɴ Kʏᴀ Kᴀʀᴏᴏɴ",
    "Tᴇʀᴇ Cʜᴇʜʀᴇ Sᴇ Nᴀᴢᴀʀ Nᴀʜɪ Hᴀᴛ’ᴛɪ",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ..",
    "Lᴀᴀʟ Bɪɴᴅɪ Mᴇɪɴ ᴛᴜ Iᴛɴɪ Sᴏɴɪ Lᴀɢᴅɪ..",
    "BY (ENGINEERGAMES)",
]
  

CRAID = [
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
    "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
    "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    "ANDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
]


RRAID = [
    "ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᗷᕼᝪᔑᗞᏆᏦᗴ",
    "しᗩᗩᗩᗯᗴᗴᗴ Ꮶᗴ ᗷᗩᗩᗩᗩᗩし",
    "ᗰᗩᗩᗩᗩᖇ ᏦᏆ ᒍᕼᗩᗩᗩᗩᎢ Ꮶᗴ ᗷᗷᗷᗷᗷᗩᗩᗩᗩᗩししししし",
    "ᗰᗩᗞᖇᑕᕼᝪᗞ..",
    "ᎢᗴᖇᏆ ᗰᗩ ᏦᏆ ᑕᕼᑌᎢ..",
    "しᗯᗞᗴ Ꮶᗴ ᗷᗩᗩᗩししし.",
    "ᗰᗩᑕᕼᗩᖇ ᏦᏆ ᒍᕼᗩᗩᎢ Ꮶᗴ ᗷᗩᗩᗩしししし",
    "ᎢᗴᖇᏆ ᗰᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰ ᗞᑌ Ꭲᗩᑭᗩ Ꭲᗩᑭ?",
    "ᎢᗴᖇᏆ ᗰᗩ Ꮶᗩ ᗷᕼᝪᔑᗞᗩᗩ",
    "ᎢᗴᖇᏆ ᗷᕼᑎ ᔑᗷᔑᗷᗴ ᗷᗞᏆ ᖇᗩᑎᗞᏆ.",
    "ᎢᗴᖇᏆ ᗰᗩ ᝪᔑᔑᗴ ᗷᗩᗞᏆ ᖇᗩᑎᗞᗞᗞᗞᗞ",
    "Ꭲᗴᖇᗩ ᗷᗩᗩᑭ ᑕᕼᏦᗩᗩᗩᗩ",
    "ᏦᏆᎢᑎᏆ ᑕᕼᝪᗞᑌ ᎢᗴᖇᏆ ᗰᗩ ᗩᗷ ᝪᖇ..",
    "ᎢᗴᖇᏆ ᗰᗩ ᑕᕼᝪᗞ ᗞᏆ ᕼᗰ ᑎᗴ",
    "ᎢᗴᖇᏆ ᗰᗩ Ꮶᗴ ᔑᎢᕼ ᖇᗴᗴしᔑ ᗷᑎᗴᏀᗩ ᖇᝪᗩᗞ ᑭᗴᗴ",
    "ᎢᗴᖇᏆ ᗰᗩ ᏦᏆ ᑕᕼᑌᎢ ᗴᏦ ᗞᗩᗰ Ꭲᝪᑭ ᔑᗴ᙭Ꭹ",
    "ᗰᗩしᑌᗰ ᑎᗩ ᑭᕼᖇ Ꮶᗴᔑᗴ しᗴᎢᗩ ᕼᑌ ᗰ ᎢᗴᖇᏆ ᗰᗩ ᏦᏆ ᑕᕼᑌᎢ Ꭲᗩᑭᗩ Ꭲᗩᑭᑭᑭᑭᑭ",
    "しᑌᑎᗞ Ꮶᗴ ᑕᕼᝪᗞᗴ Ꭲᑌ ᏦᗴᖇᗴᏀᗩ ᎢᎩᑭᏆᑎ",
    "ᔑᑭᗴᗴᗞ ᑭᏦᗞ しᗯᗞᗴᗴᗴᗴ",
    "ᗷᗩᗩᑭ ᏦᏆ ᔑᑭᗴᗴᗞ ᗰᎢᑕᕼ Ꮶᖇᖇᖇ",
    "しᗯᗞᗴᗴᗴ",
    "ᑭᗩᑭᗩ ᏦᏆ ᔑᑭᗴᗴᗞ ᗰᎢᑕᕼ ᑎᕼᏆ ᕼᝪ ᖇᕼᏆ ᏦᎩᗩ",
    "ᗩしᗴ ᗩしᗴ ᗰᗴしᗩ ᗷᑕᕼᗩᗩᗩᗩ",
    "ᑕᕼᑌᗞ ᏀᎩᗩ ᑭᗩᑭᗩ ᔑᗴᗴᗴ",
    "ᏦᏆᔑᗩᑎ Ꮶᝪ Ꮶᕼᝪᗞᑎᗩ ᝪᖇ",
    "ᔑᗩしᗴ ᖇᗩᑭᗴᏦし ᏦᖇᗞᏦᗩ Ꭲᗴᖇᗩ",
    "ᕼᗩᕼᗩᕼᗩᗩᗩᗩᗩ",
    "ᏦᏆᗞᔑᔑᔑᔑ",
    "ᎢᗴᖇᏆ ᗰᗩ ᑕᕼᑌᗞ ᏀᎩᏆ ᗩᗷ ᖴᖇᗩᖇ ᗰᎢ ᕼᝪᑎᗩ",
    "Ꭹᗴ しᗞᑎᏀᗴ ᗷᗩᑭᑭ ᔑᗴ",
    "ᏦᏆᗞᔑᔑᔑ ᖴᖇᗩᖇ ᕼᗩᕼᗩᕼᕼ",
    "ᗷᕼᗴᑎ Ꮶᗴ しᗯᗞᗴ ᔑᕼᖇᗰ Ꮶᖇ",
    "ᏦᏆᎢᑎᏆ ᏀしᏆᎩᗩ ᑭᗞᗯᗴᏀᗩ ᗩᑭᑎᏆ ᗰᗩ Ꮶᝪ",
    "ᑎᗩししᗴᗴ",
    "ᔑᑌᗩᖇ Ꮶᗴ ᑭᏆししᗴ ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᔑᗩᗞᗩᏦ ᑭᖇ しᏆᎢᗩᏦᗴ ᑕᕼᝪᗞ ᗞᑌᑎᏀᗩ 😂😆🤤",
    "ᗩᗷᗴ ᎢᗴᖇᏆ ᗰᗩᗩᏦᗩ ᗷᕼᝪᔑᗞᗩ ᗰᗩᗞᗴᖇᑕᕼᝪᝪᗞ Ꮶᖇ ᑭᏆししᗴ ᑭᗩᑭᗩ ᔑᗴ しᗩᗞᗴᏀᗩ Ꭲᑌ 😼😂🤤",
    "ᏀᗩしᏆ ᏀᗩしᏆ ᑎᗴ ᔑᕼᝪᖇ ᕼᗴ ᎢᗴᖇᏆ ᗰᗩᗩ ᖇᗩᑎᗞᏆ ᑕᕼᝪᖇ ᕼᗴ 💋💋💦",
    "ᗩᗷᗴ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᝪ ᑕᕼᝪᗞᑌ ᖇᗩᑎᗞᏆᏦᗴ ᑭᏆししᗴ ᏦᑌᎢᎢᗴ Ꮶᗴ ᑕᕼᝪᗞᗴ 😂👻🔥",
    "ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᗩᏆᔑᗴ ᑕᕼᝪᗞᗩ ᗩᏆᔑᗴ ᑕᕼᝪᗞᗩ ᎢᗴᖇᏆ ᗰᗩᗩᗩ ᗷᗴᗞ ᑭᗴᕼᏆ ᗰᑌᎢᕼ ᗞᏆᗩ 💦💦💦💦",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᗴ ᗷᕼᝪᔑᗞᗴ ᗰᗴ ᗩᗩᗩᏀ しᗩᏀᗩᗞᏆᗩ ᗰᗴᖇᗩ ᗰᝪᎢᗩ しᑌᑎᗞ ᗞᗩしᏦᗴ 🔥🔥💦😆😆",
    "ᖇᗩᑎᗞᏆᏦᗴ ᗷᗩᑕᕼᕼᗴ ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᑕᕼᝪᗞᑌ ᑕᕼᗩし ᑎᏆᏦᗩし",
    "ᏦᏆᎢᑎᗩ ᑕᕼᝪᗞᑌ ᎢᗴᖇᏆ ᖇᗩᑎᗞᏆ ᗰᗩᗩᏦᏆ ᑕᕼᑌᎢᕼ ᗩᗷᗷ ᗩᑭᑎᏆ ᗷᗴᕼᗴᑎ Ꮶᝪ ᗷᕼᗴᒍ 😆👻🤤",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᏦᝪᎢᝪ ᑕᕼᝪᗞ ᑕᕼᝪᗞᏦᗴ ᑭᑌᖇᗩ ᖴᗩᗩᗞ ᗞᏆᗩ ᑕᕼᑌᎢᕼ ᗩᗷᗷ ᎢᗴᖇᏆ Ꮐᖴ Ꮶᝪ ᗷᕼᗴᒍ 😆💦🤤",
    "ᎢᗴᖇᏆ Ꮐᖴ Ꮶᝪ ᗴᎢᑎᗩ ᑕᕼᝪᗞᗩ ᗷᗴᕼᗴᑎ Ꮶᗴ しᝪᗞᗴ ᎢᗴᖇᏆ Ꮐᖴ Ꭲᝪ ᗰᗴᖇᏆ ᖇᗩᑎᗞᏆ ᗷᗩᑎᏀᗩᎩᏆ ᗩᗷᗷ ᑕᕼᗩし ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᑕᕼᝪᗞᎢᗩ ᖴᏆᖇᔑᗴ ♥️💦😆😆😆😆",
    "ᕼᗩᖇᏆ ᕼᗩᖇᏆ Ꮐᕼᗩᗩᔑ ᗰᗴ ᒍᕼᝪᑭᗞᗩ ᎢᗴᖇᏆ ᗰᗩᗩᏦᗩ ᗷᕼᝪᔑᗞᗩ 🤣🤣💋💦",
    "ᑕᕼᗩし Ꭲᗴᖇᗴ ᗷᗩᗩᑭ Ꮶᝪ ᗷᕼᗴᒍ Ꭲᗴᖇᗩ ᗷᗩᔑᏦᗩ ᑎᕼᏆ ᕼᗴ ᑭᗩᑭᗩ ᔑᗴ しᗩᗞᗴᏀᗩ Ꭲᑌ",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᏦᏆ ᑕᕼᑌᎢᕼ ᗰᗴ ᗷᝪᗰᗷ ᗞᗩしᏦᗴ ᑌᗞᗩ ᗞᑌᑎᏀᗩ ᗰᗩᗩᏦᗴ しᗩᗯᗞᗴ",
    "ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᎢᖇᗩᏆᑎ ᗰᗴ しᗴᒍᗩᏦᗴ Ꭲᝪᑭ ᗷᗴᗞ ᑭᗴ しᏆᎢᗩᏦᗴ ᑕᕼᝪᗞ ᗞᑌᑎᏀᗩ ᔑᑌᗩᖇ Ꮶᗴ ᑭᏆししᗴ 🤣🤣💋💋",
    "ᎢᗴᖇᏆ ᗰᗩᗩᗩᏦᗴ ᑎᑌᗞᗴᔑ ᏀᝪᝪᏀしᗴ ᑭᗴ ᑌᑭしᝪᗩᗞ ᏦᗩᖇᗞᑌᑎᏀᗩ ᗷᗴᕼᗴᑎ Ꮶᗴ しᗩᗴᗯᗞᗴ 👻🔥",
    "ᎢᗴᖇᏆ ᗰᗩᗩᗩᏦᗴ ᑎᑌᗞᗴᔑ ᏀᝪᝪᏀしᗴ ᑭᗴ ᑌᑭしᝪᗩᗞ ᏦᗩᖇᗞᑌᑎᏀᗩ ᗷᗴᕼᗴᑎ Ꮶᗴ しᗩᗴᗯᗞᗴ 👻🔥",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᝪ ᑕᕼᝪᗞ ᑕᕼᝪᗞᏦᗴ ᐯᏆᗞᗴᝪ ᗷᗩᑎᗩᏦᗴ ᙭ᑎ᙭᙭.ᑕᝪᗰ ᑭᗴ ᑎᗴᗴしᗩᗰ ᏦᗩᖇᗞᑌᑎᏀᗩ ᏦᑌᎢᎢᗴ Ꮶᗴ ᑭᏆししᗴ 💦💋",
    "ᎢᗴᖇᏆ ᗰᗩᗩᗩᏦᏆ ᑕᕼᑌᗞᗩᏆ Ꮶᝪ ᑭᝪᖇᑎᕼᑌᗷ.ᑕᝪᗰ ᑭᗴ ᑌᑭしᝪᗩᗞ ᏦᗩᖇᗞᑌᑎᏀᗩ ᔑᑌᗩᖇ Ꮶᗴ ᑕᕼᝪᗞᗴ 🤣💋💦",
    "ᗩᗷᗴ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᝪ ᑕᕼᝪᗞᑌ ᖇᗩᑎᗞᏆᏦᗴ ᗷᗩᑕᕼᕼᗴ ᎢᗴᖇᗴᏦᝪ ᑕᕼᗩᏦᏦᝪ ᔑᗴ ᑭᏆしᗯᗩᐯᑌᑎᏀᗩ ᖇᗩᑎᗞᏆᏦᗴ ᗷᗩᑕᕼᕼᗴ 🤣🤣",
    "ᎢᗴᖇᏆ ᗰᗩᗩᏦᏆ ᑕᕼᑌᎢᕼ ᖴᗩᗩᗞᏦᗴ ᖇᗩᏦᗞᏆᗩ ᗰᗩᗩᏦᗴ しᝪᗞᗴ ᒍᗩᗩ ᗩᗷᗷ ᔑᏆしᗯᗩしᗴ 👄👄",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᏦᏆ ᑕᕼᑌᎢᕼ ᗰᗴ ᗰᗴᖇᗩ しᑌᑎᗞ Ꮶᗩᗩしᗩ",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ しᗴᎢᏆ ᗰᗴᖇᏆ しᑌᑎᗞ ᗷᗩᗞᗴ ᗰᗩᔑᎢᏆ ᔑᗴ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᝪ ᗰᗴᑎᗴ ᑕᕼᝪᗞ ᗞᗩしᗩ ᗷᝪᕼᝪᎢ ᔑᗩᔑᎢᗴ ᔑᗴ",
    "ᗷᗴᎢᗴ Ꭲᑌ ᗷᗩᗩᑭ ᔑᗴ しᗴᏀᗩ ᑭᗩᑎᏀᗩ ᎢᗴᖇᏆ ᗰᗩᗩᗩ Ꮶᝪ ᑕᕼᝪᗞ ᗞᑌᑎᏀᗩ ᏦᗩᖇᏦᗴ ᑎᗩᑎᏀᗩ 💦💋",
    "ᕼᗩᕼᗩᕼᗩᕼ ᗰᗴᖇᗴ ᗷᗴᎢᗴ ᗩᏀしᏆ ᗷᗩᗩᖇ ᗩᑭᑎᏆ ᗰᗩᗩᏦᝪ しᗴᏦᗴ ᗩᗩᎩᗩ ᗰᗩᎢᕼ ᏦᗩᎢ ᝪᖇ ᗰᗴᖇᗴ ᗰᝪᎢᗴ しᑌᑎᗞ ᔑᗴ ᑕᕼᑌᗞᗯᗩᎩᗩ ᗰᗩᎢᕼ Ꮶᗩᖇ",
    "ᑕᕼᗩし ᗷᗴᎢᗩ Ꭲᑌᒍᕼᗴ ᗰᗩᗩᖴ ᏦᏆᗩ 🤣 ᗩᗷᗷ ᗩᑭᑎᏆ Ꮐᖴ Ꮶᝪ ᗷᕼᗴᒍ",
    "ᔑᕼᗩᖇᗩᗰ Ꮶᗩᖇ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᗩ ᗷᕼᝪᔑᗞᗩ ᏦᏆᎢᑎᗩ ᏀᗩᗩしᏆᗩ ᔑᑌᑎᗯᗩᎩᗴᏀᗩ ᗩᑭᑎᏆ ᗰᗩᗩᗩ ᗷᗴᕼᗴᑎ Ꮶᗴ ᑌᑭᗴᖇ",
    "ᗩᗷᗴ ᖇᗩᑎᗞᏆᏦᗴ ᗷᗩᑕᕼᕼᗴ ᗩᑌᏦᗩᎢ ᑎᕼᏆ ᕼᗴᎢᝪ ᗩᑭᑎᏆ ᖇᗩᑎᗞᏆ ᗰᗩᗩᏦᝪ しᗴᏦᗴ ᗩᗩᎩᗩ ᗰᗩᎢᕼ Ꮶᗩᖇ ᕼᗩᕼᗩᕼᗩᕼᗩ",
    "ᏦᏆᗞᏃ ᗰᗩᗞᗩᖇᑕᕼᝪᗞ ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᑕᕼᝪᗞ ᑕᕼᝪᗞᏦᗴ Ꭲᗴᖇᖇ しᏆᎩᗴ ᗷᕼᗩᏆ ᗞᗴᗞᏆᎩᗩ",
    "ᒍᑌᑎᏀしᗴ ᗰᗴ ᑎᗩᑕᕼᎢᗩ ᕼᗴ ᗰᝪᖇᗴ ᎢᗴᖇᏆ ᗰᗩᗩᏦᏆ ᑕᕼᑌᗞᗩᏆ ᗞᗴᏦᏦᗴ ᔑᗩᗷ ᗷᝪしᎢᗴ ᝪᑎᑕᗴ ᗰᝪᖇᗴ ᝪᑎᑕᗴ ᗰᝪᖇᗴ 🤣🤣💦💋",
    "ᏀᗩしᏆ ᏀᗩしᏆ ᗰᗴ ᖇᗴᕼᎢᗩ ᕼᗴ ᔑᗩᑎᗞ ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᑕᕼᝪᗞ ᗞᗩしᗩ ᝪᖇ ᗷᗩᑎᗩ ᗞᏆᗩ ᖇᗩᑎᗞ 🤤🤣",
    "ᔑᗩᗷ ᗷᝪしᎢᗴ ᗰᑌᒍᕼᏦᝪ ᑭᗩᑭᗩ ᏦᎩᝪᑌᑎᏦᏆ ᗰᗴᑎᗴ ᗷᗩᑎᗩᗞᏆᗩ ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᑭᖇᗴᏀᑎᗴᑎᎢ 🤣🤣",
    "ᔑᑌᗩᖇ Ꮶᗴ ᑭᏆししᗴ ᎢᗴᖇᏆ ᗰᗩᗩᏦᏆ ᑕᕼᑌᎢᕼ ᗰᗴ ᔑᑌᗩᖇ Ꮶᗩ しᝪᑌᗞᗩ ᝪᖇ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᏦᏆ ᑕᕼᑌᎢᕼ ᗰᗴ ᗰᗴᖇᗩ しᝪᗞᗩ",
    "ᑕᕼᗩし ᑕᕼᗩし ᗩᑭᑎᏆ ᗰᗩᗩᏦᏆ ᑕᕼᑌᑕᕼᏆᎩᗩ ᗞᏆᏦᗩ",
    "ᕼᗩᕼᗩᕼᗩᕼᗩ ᗷᗩᑕᕼᕼᗴ ᎢᗴᖇᏆ ᗰᗩᗩᗩᏦᝪ ᑕᕼᝪᗞ ᗞᏆᗩ ᑎᗩᑎᏀᗩ ᏦᗩᖇᏦᗴ",
    "ᎢᗴᖇᏆ Ꮐᖴ ᕼᗴ ᗷᗩᗞᏆ ᔑᗴ᙭Ꭹ ᑌᔑᏦᝪ ᑭᏆしᗩᏦᗴ ᑕᕼᝪᝪᗞᗴᑎᏀᗴ ᑭᗴᑭᔑᏆ",
    "2 ᖇᑌᑭᗩᎩ ᏦᏆ ᑭᗴᑭᔑᏆ ᎢᗴᖇᏆ ᗰᑌᗰᗰᎩ ᔑᗩᗷᔑᗴ ᔑᗴ᙭Ꭹ 💋💦",
    "ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ ᑕᕼᗴᗴᗰᔑ ᔑᗴ ᑕᕼᑌᗞᗯᗩᐯᑌᑎᏀᗩ ᗰᗩᗞᗴᖇᑕᕼᝪᝪᗞ Ꮶᗴ ᑭᏆししᗴ 💦🤣",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᏦᏆ ᑕᕼᑌᎢᕼ ᗰᗴ ᗰᑌᎢᕼᏦᗴ ᖴᗩᖇᗩᖇ ᕼᝪᒍᗩᐯᑌᑎᏀᗩ ᕼᑌᏆ ᕼᑌᏆ ᕼᑌᏆ",
    "ᔑᑭᗴᗴᗞ しᗩᗩᗩ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᑕᕼᝪᗞᑌ ᖇᗩᑎᗞᏆᏦᗴ ᑭᏆししᗴ 💋💦🤣",
    "ᗩᖇᗴ ᖇᗴ ᗰᗴᖇᗴ ᗷᗴᎢᗴ ᏦᎩᝪᑌᑎ ᔑᑭᗴᗴᗞ ᑭᗩᏦᗩᗞ ᑎᗩ ᑭᗩᗩᗩ ᖇᗩᕼᗩ ᗩᑭᑎᗴ ᗷᗩᗩᑭ Ꮶᗩ ᕼᗩᕼᗩᕼ🤣🤣",
    "ᔑᑌᑎ ᔑᑌᑎ ᔑᑌᗩᖇ Ꮶᗴ ᑭᏆししᗴ ᒍᕼᗩᑎᎢᝪ Ꮶᗴ ᔑᝪᑌᗞᗩᏀᗩᖇ ᗩᑭᑎᏆ ᗰᑌᗰᗰᎩ ᏦᏆ ᑎᑌᗞᗴᔑ ᗷᕼᗴᒍ",
    "ᗩᗷᗴ ᔑᑌᑎ しᝪᗞᗴ ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ Ꮶᗩ ᗷᕼᝪᔑᗞᗩ ᖴᗩᗩᗞ ᗞᑌᑎᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩᏦᝪ Ꮶᕼᑌしᗴ ᗷᗩᒍᗩᖇ ᗰᗴ ᑕᕼᝪᗞ ᗞᗩしᗩ 🤣🤣💋",
    "ᔑᕼᖇᗰ Ꮶᖇ",
    "ᗰᗴᖇᗴ しᑌᑎᗞ Ꮶᗴ ᗷᗩᗩᗩᗩᗩししししし",
    "ᏦᏆᎢᑎᏆ ᏀしᏆᎩᗩ ᑭᗞᗯᎩᏀᗩ ᗩᑭᑎᏆ ᗰᗩ ᗷᕼᗴᑎ Ꮶᝪ",
    "ᖇᑎᗞᏆ Ꮶᗴ しᗞᏦᗴᗴᗴᗴᗴᗴᗴᗴᗴ",
    "ᏦᏆᗞᔑᔑᔑᔑᔑᔑᔑᔑᔑᔑᔑᔑ",
    "ᗩᑭᑎᏆ Ꮐᗩᗩᑎᗞ ᗰᗴᏆᑎ ᗰᑌᎢᕼᏆ ᗞᗩᗩし",
    "ᗩᑭᑎᏆ しᑌᑎᗞ ᑕᕼᝪᝪᔑ",
    "ᗩᑭᑎᏆ ᗰᗩ Ꮶᝪ ᒍᗩ ᑕᕼᝪᝪᔑ",
    "ᗷᕼᗴᑎ Ꮶᗴ しᗩᑌᗞᗴ",
    "ᗷᕼᗴᑎ Ꮶᗴ ᎢᗩᏦᏦᗴ",
    "ᗩᗷしᗩ Ꭲᗴᖇᗩ Ꮶᕼᗩᑎ ᗞᗩᑎ ᑕᕼᝪᗞᑎᗴ ᏦᏆ ᗷᗩᖇᏆᏆᏆ",
    "ᗷᗴᎢᗴ ᎢᗴᖇᏆ ᗰᗩ ᔑᗷᔑᗴ ᗷᗞᏆ ᖇᗩᑎᗞ",
    "しᑌᑎᗞ Ꮶᗴ ᗷᗩᗩᗩし ᒍᕼᗩᎢ Ꮶᗴ ᑭᏆᔑᔑᔑᑌᑌᑌᑌᑌᑌᑌ",
    "しᑌᑎᗞ ᑭᗴ しᎢᏦᏆᎢ ᗰᗩᗩᗩしししし ᏦᏆ ᗷᝪᑎᗞ ᕼ Ꭲᑌᑌᑌ",
    "Ꮶᗩᔑᕼ ᝪᔑ ᗞᏆᑎ ᗰᑌᎢᕼ ᗰᖇᏦᗴ ᔑᝪᒍᎢᗩ ᗰ Ꭲᑌᑎ ᑭᗩᏆᗞᗩ ᑎᗩ ᕼᝪᎢᗩᗩ",
    "ᏀしᎢᏆ ᏦᖇᗞᏆ Ꭲᑌᒍᗯ ᑭᗩᏆᗞᗩ ᏦᖇᏦᗴ",
    "ᔑᑭᗴᗴᗞ ᑭᏦᗞᗞᗞ",
    "Ꮐᗩᗩᑎᗞ ᗰᗩᏆᑎ しᗯᗞᗩ ᗞᗩし しᗴ ᗩᑭᑎᏆ ᗰᗴᖇᗩᗩᗩ",
    "Ꮐᗩᗩᑎᗞ ᗰᗴᏆᑎ ᗷᗩᗰᗷᑌ ᗞᗴᗞᑌᑎᏀᗩᗩᗩᗩᗩᗩ",
    "Ꮐᗩᑎᗞ ᖴᎢᏆ Ꮶᗴ ᗷᗩしᏦᏦᏦ",
    "ᏀᝪᎢᗴ ᏦᏆᎢᑎᗴ ᗷᕼᏆ ᗷᗩᗞᗴ ᕼᝪ, しᑌᑎᗞ Ꮶᗴ ᑎᏆᑕᕼᗴ ᕼᏆ ᖇᗴᕼᎢᗴ ᕼᗩᏆ",
    "ᕼᗩᏃᗩᗩᖇ しᑌᑎᗞ ᎢᗴᖇᏆ Ꮐᗩᗩᑎᗞ ᗰᗩᏆᑎ",
    "ᒍᕼᗩᗩᑎᎢ Ꮶᗴ ᑭᏆᔑᔑᑌ-",
    "ᎢᗴᖇᏆ ᗰᗩ ᏦᏆ ᏦᗩしᏆ ᑕᕼᑌᎢ",
    "ᏦᕼᝪᎢᗴᎩ ᏦᏆ ᗩᑌしᗞᗩ",
    "ᏦᑌᎢᎢᗴ Ꮶᗩ ᗩᗯしᗩᎢ",
    "ᏦᑌᎢᎢᗴ ᏦᏆ ᒍᗩᎢ",
    "ᏦᑌᎢᎢᗴ Ꮶᗴ ᎢᗩᎢᎢᗴ",
    "ᎢᗴᎢᏆ ᗰᗩ ᏦᏆ.ᑕᕼᑌᎢ , ᎢᗴᖇᏆ ᗰᗩ ᖇᑎᗞᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆᏆ",
    "しᗩᐯᗞᗴ Ꮶᗴ ᗷᗩし",
    "ᗰᑌᕼ ᗰᗴᏆ しᗴしᗴ",
    "しᑌᑎᗞ Ꮶᗴ ᑭᗩᔑᏆᑎᗴ",
    "ᗰᗴᖇᗴ しᗯᗞᗴ Ꮶᗴ ᗷᗩᗩᗩᗩᗩししし",
    "ᕼᗩᕼᗩᕼᗩᗩᗩᗩᗩᗩ",
    "ᑕᕼᑌᗞ ᏀᎩᗩᗩᗩᗩᗩ",
    "ᖇᗩᑎᗞᏆ Ꮶᕼᗩᑎᗴ ᏦᏆ ᑌしᗩᗞᗞᗞ",
    "ᔑᗩᗞᏆ ᕼᑌᏆ Ꮐᗩᗩᑎᗞ",
    "ᎢᗴᖇᏆ Ꮐᗩᗩᑎᗞ ᗰᗩᏆᑎ ᏦᑌᎢᗴ Ꮶᗩ しᑌᑎᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᗩ ᗷᕼᝪᔑᗞᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ",
    "Ꭲᗴᖇᗴ Ꮐᗩᗩᑎᗞ ᗰᗴᏆᑎ Ꮶᗴᗴᗞᗴ ᑭᗩᗞᗩᎩ",
    "ᑌししᑌ Ꮶᗴ ᑭᗩᎢᕼᗴ",
    "ᔑᑌᑎᑎ ᗰᗩᗞᗴᖇᑕᕼᝪᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᗩ ᗷᕼᝪᔑᗞᗩ",
    "ᗷᗴᕼᗴᑎ Ꮶ しᑌᑎᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᗩ ᑕᕼᑌᎢ ᏦᏆ ᑕᕼᎢᑎᏆᏆᏆᏆ",
    "ᗰᗴᖇᗩ しᗩᗯᗞᗩ しᗴしᗴ Ꭲᑌ ᗩᏀᗩᖇ ᑕᕼᗩᏆᎩᗴ Ꭲᝪᕼ",
    "Ꮐᗩᗩᑎᗞᑌ",
    "ᑕᕼᑌᎢᏆᎩᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᑭᗴ ᒍᑕᗷ ᑕᕼᗩᗞᕼᗩᗩ ᗞᑌᑎᏀᗩ",
    "ᔑᗩᗰᒍᕼᗩᗩ しᗩᗯᗞᗴ",
    "Ꭹᗩ ᗞᑌ Ꭲᗴᖇᗴ Ꮐᗩᗩᑎᗞ ᗰᗴ Ꭲᗩᑭᗩᗩ Ꭲᗩᑭ��",
    "ᎢᗴᖇᏆ ᗷᗴᕼᗴᑎ ᗰᗴᖇᗩ ᖇᝪᏃ しᗴᎢᏆ ᕼᗩᏆ",
    "ᎢᗴᖇᏆ Ꮐᖴ Ꮶ ᔑᗩᗩᎢᕼ ᗰᗰᔑ ᗷᗩᑎᗩᗩ ᑕᕼᑌᏦᗩ ᕼᑌ���不�不",
    "Ꭲᑌ ᑕᕼᑌᎢᏆᎩᗩ Ꭲᗴᖇᗩ Ꮶᕼᗩᑎᗞᗩᗩᑎ ᑕᕼᑌᎢᏆᎩᗩ",
    "ᗩᑌᖇ ᏦᏆᎢᑎᗩ ᗷᝪしᑌ ᗷᗴᎩ ᗰᗩᑎᑎ ᗷᕼᗩᖇ ᏀᗩᎩᗩ ᗰᗴᖇᗩ�不",
    "ᎢᗴᖇᏆᏆᏆᏆᏆᏆ ᗰᗩᗩᗩᗩ ᏦᏆ ᑕᕼᑌᎢᎢᎢ ᗰᗴ ᗩᗷᑕᗞ しᏆᏦᕼ ᗞᑌᑎᏀᗩ ᗰᗩᗩ Ꮶᗴ しᝪᗞᗴ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᝪ しᗴᏦᗩᖇ ᗰᗩᏆ ᖴᗩᖇᗩᖇ",
    "ᖇᗩᑎᏆᗞᏆᏆᏆ",
    "ᗷᗩᑕᕼᗴᗴ",
    "ᑕᕼᝪᗞᑌ",
    "ᖇᗩᑎᗞᏆ",
    "ᖇᗩᑎᗞᏆ Ꮶᗴ ᑭᏆししᗴ",
    "ᎢᗴᖇᏆᏆᏆᏆᏆ ᗰᗩᗩᗩ Ꮶᝪ ᗷᕼᗴᒍᒍᒍ",
    "Ꭲᗴᖇᗩᗩ ᗷᗩᗩᗩᗩᑭ ᕼᑌ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰᗴ ᕼᗩᗩᎢ ᗞᗩᗩししᏦᗴ ᗷᕼᗩᗩᏀ ᒍᗩᗩᑎᑌᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᝪ ᔑᗩᖇᗩᏦ ᑭᗴ しᗴᎢᗩᗩ ᗞᑌᑎᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᝪ Ꮐᗷ ᖇᝪᗩᗞ ᑭᗴ しᗴᒍᗩᏦᗴ ᗷᗴᑕᕼ ᗞᑌᑎᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰᗴ́ ᏦᗩᗩしᏆ ᗰᏆᎢᑕᕼ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᔑᗩᔑᎢᏆ ᖇᗩᑎᗞᏆ ᕼᗩᏆ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰᗴ ᏦᗩᗷᑌᎢᗩᖇ ᗞᗩᗩし Ꮶᗴ ᔑᝪᑌᑭ ᗷᗩᑎᗩᑌᑎᏀᗩ ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩᗩ ᖇᗩᑎᗞᏆ ᕼᗩᏆ",
    "ᎢᗴᖇᏆ ᗰᗩᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰᗴ ᗞᗴᎢᝪし ᗞᗩᗩし ᗞᑌᑎᏀᗩ ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᗩᗩᗩ ᗷᕼᝪᔑᗞᗩᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰᗴ しᗩᑭᎢᝪᑭ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᖇᗩᑎᗞᏆ ᕼᗩᏆ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᝪ ᗷᏆᔑᎢᗩᖇ ᑭᗴ しᗴᎢᗩᗩᏦᗴ ᑕᕼᝪᗞᑌᑎᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᝪ ᗩᗰᗴᖇᏆᑕᗩ ᏀᕼᑌᗰᗩᗩᑌᑎᏀᗩ ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ ᏦᏆ ᑕᕼᑌᎢ ᗰᗴ ᑎᗩᗩᖇᏆᎩᗩし ᑭᕼᝪᖇ ᗞᑌᑎᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᗴ Ꮐᗩᑎᗞ ᗰᗴ ᗞᗴᎢᝪし ᗞᗩᗩし ᗞᑌᑎᏀᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩᗩ Ꮶᝪ ᕼᝪᖇしᏆᑕᏦᔑ ᑭᏆしᗩᑌᑎᏀᗩ ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᝪ ᔑᗩᖇᗩᏦ ᑭᗴ しᗴᎢᗩᗩᗩ ᗞᑌᑎᏀᗩᗩᗩ",
    "ᎢᗴᖇᏆ ᗰᗩᗩ Ꮶᗩᗩ ᗷᕼᝪᔑᗞᗩ",
    "ᗰᗴᖇᗩᗩᗩ しᑌᑎᗞ ᑭᗩᏦᗩᗞ しᗴ ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᑕᕼᑌᑭ ᎢᗴᖇᏆ ᗰᗩᗩ ᗩᏦᗩᗩ ᗷᕼᝪᔑᗞᗩᗩ",
    "ᎢᗴᖇᏆᏆᏆ ᗰᗩᗩ ᑕᕼᑌᖴ ᏀᗴᎩᏆᏆ ᏦᎩᗩᗩᗩ しᗩᗯᗞᗴᗴᗴ",
    "ᎢᗴᖇᏆᏆᏆ ᗰᗩᗩ Ꮶᗩᗩ ᗷᒍᔑᝪᗞᗩᗩᗩ",
    "ᗰᗩᗞᗩᖇ᙭ᕼᝪᗞᗞᗞ",
    "ᎢᗴᖇᏆᑌᑌᏆ ᗰᗩᗩᗩ Ꮶᗩᗩ ᗷᕼᔑᝪᗞᗩᗩᗩ",
    "ᎢᗴᖇᏆᏆᏆᏆᏆᏆ ᗷᗴᕼᗴᑎᑎᑎᑎ Ꮶᝪ ᑕᕼᝪᗞᗞᗞᑌᑌᑌᑌ ᗰᗩᗞᗩᖇ᙭ᕼᝪᗞᗞᗞᗞ",
    "ᑎᏆᏦᗩし ᗰᗩᗞᗩᖇᑕᕼᝪᗞ",
    "ᖇᗩᑎᗞᏆ Ꮶᗴ ᗷᗩᑕᕼᗴ",
    "Ꭲᗴᖇᗩ ᗰᗩᗩ ᗰᗴᖇᏆ ᖴᗩᑎ",
    "ᎢᗴᖇᏆ ᔑᗴ᙭Ꭹ ᗷᗩᕼᗴᑎ ᏦᏆ ᑕᕼᑌᎢ ᝪᑭ",
]

KARPITSPAM = [5088683114, 5098147320]


PORNSPAM = [
        "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
        "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
        "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
        "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
        "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
        "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
        "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
        "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
        "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
        "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
        "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
        "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
        "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
        "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
        "https://telegra.ph/file/50637aa9c04d136687523.mp4",
        "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
        "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
        "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
        "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
        "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
        "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
        "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
        "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
        "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
        "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
        "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
        "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
        "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
        "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
        "https://telegra.ph/file/f483400ff141de73767ca.jpg",
        "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
        "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
        "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
        "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
        "https://telegra.ph/file/b434999287d3580250960.jpg",
        "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
        "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
        "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
        "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
        "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
        "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
        "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
        "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
        "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
        "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
        "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
        "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
        "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
        "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
        "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
        "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
        "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
        "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
        "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
]

OWORD = [
    "AAJA",
    "BHEN",
    "KE",
    "LUND",
    "TERII",
    "MÁÀA",
    "KI",
    "CHUÚTT",
    "MEE",
    "TEL",
    "LAGA",
    "KEE",
    "SARIYAAA",
    "DALUNGAAA",
    "BHOSDIKE",
    "ABB",
    "TUU",
    "SIKHAYEGA",
    "BAAP",
    "KO",
    "CHØDNÂ",
    "HAA",
    "RÆNDIIII",
    "KE",
    "PILEE",
    "TERI",
    "MÁÀ",
    "KI",
    "GAND",
    "ME",
    "CHURINYE",
    "KAAT",
    "RAHE",
    "HAI",
    "BSDKE",
    "SPEED",
    "PAKADNA",
    "SIKHHH",
    "BAAP",
    "KI",
    "SAMJHA",
    "BHENCHØD",
    "AUKAT",
    "BANA",
    "RÆNDII",
    "TERI",
    "KO",
    "NACHUNGA",
    "NANGI",
    "ON",
    "ROAD",
    "SAMJHA",
    "MADARCXHOD",
    "LAWDE"
    "MÂÂDARCHØD",
    "RÆNDI",
    "KE",
    "BACHHHE",
    "KALLLLLAP",
    "MATTT",
    "BAAAAP"
    "SEEE",
    "AAAAAAAAJ",
    "TERRRRRRRRE",
    "KHANDAAAAN KO CHØDUNGA",
    "TERI",
    "BAHANNNNNN",
    "KA",
    "BHOOXXXXXXDA",
    "BAAAAAAAAP",
    "SPEEEEEEEEEEED"
    "SPEEEED",
    "MATCHHHHH",
    "KARRRRRLLLE",
    "PAHLE",
    "LAWDE KE",
    "BALLLLLLL",
    "ABBBBBBB KITNNNA",
    "TERIIIIIIIIIIIIIII",
    "MÁÀAAAAA",
    "KOOOOOOO",
    "CHHHHHHODU",
    "TERIIIIIII",
    "KEEEEEEE",
    "BOOOOOOOOOOOOR",
    "MEEE",
    "SARIYAAAAA",
    "DALLLLLLLL",
    "DUNGAAA",
    "TERI",
    "BEHN",
    "KI",
    "CHUÚTTT",
    "MEEEE",
    "KELE",
    "KE",
    "CHILKE",
    "🍌🍌😍",
    "TERI",
    "VAHEEN",
    "DHANDHE",
    "VAALI 😋😛",
    "TERI",
    "MÁÀ",
    "KE",
    "BHOSDE",
    "ME",
    "DUNGA",
    "SAARI",
    "GARMI",
    "NIKAL",
    "JAAYEGI",
    "TERI",
    "VAHEEN",
    "KO",
    "APNAAA",
    "SEMEN",
    "PEELAUNGA",
    "MÂÂDARCHØD😚",
    "TERI",
    "MÁÀ",
    "KI",
    "GAAND",
    "ME",
    "SARIYA",
    "DAAL"
    "DUNGA",
    "MÂÂDARCHØD",
    "USI",
    "SARIYE",
    "PRRRRR",
    "TANG",
    "KE",
    "BACHE",
    "PAIDA",
    "HONGE 😱😱",
    "TERI",
    "MÁÀ",
    "KO",
    "KOLKATA",
    "VAALE",
    "JITU",
    "BHAIYA",
    "KA",
    "LUND",
    "MUBARAK",
    "TERI",
    "MUMMY",
    "KI",
    "FANTASY",
    "HU",
    "LAWDE",
    "TU",
    "APNI",
    "BHEN",
    "KO",
    "SMBHAAL 😈",
    "TERI",
    "MÁÀAA",
    "KAA",
    "RAPE",
    "KAR",
    "DAALA",
    "BSDKE",
    "AUKAT",
    "BANA",
    "RÆNDI",
    "KE",
    "PILLE",
    "THORI",
    "MÁÀ",
    " KAA",
    "BOOR",
    "FADDU",
    "RÆNDI",
    "KE",
    "CHØDE",
    "KALAP",
    "GYA",
    "BSDKE",
    "YAHI",
    "AUKAT",
    "HAA",
    "RÆNDI",
    "KE",
    "CHØDEEE",
    "ITNA",
    "KALAP",
    "RAHA",
    "BSDKE",
    "ROO",
    "GYA",
    "RÆNDI",
    "KALAP",
    "BHEN",
    "KE",
    "LODE",
    "ROO",
    "MAT",
    "CP",
    "BOLKE",
]

KARPITSPAM = [5088683114, 5098147320]
